import { randomUUID } from 'node:crypto';
import type { Database } from '@autoserver/database';

function safeUrl(value?:string){if(!value)return undefined;const u=new URL(value);if(!['https:','http:'].includes(u.protocol))throw new Error('RESOURCE_URL_PROTOCOL_INVALID');return u.toString();}
export class EducationRepository{
  constructor(private readonly database:Database){}
  async submitResource(input:{guildId:string;userId:string;subject:string;title:string;url?:string;notes?:string}){if(input.subject.trim().length<2||input.title.trim().length<3)throw new Error('EDUCATION_RESOURCE_INVALID');const resourceId=randomUUID();await this.database.requirePool().query(`insert into education_resources(resource_id,guild_id,submitter_user_id,subject,title,url,notes,status) values($1,$2,$3,$4,$5,$6,$7,'REVIEW')`,[resourceId,input.guildId,input.userId,input.subject.trim().slice(0,80),input.title.trim().slice(0,160),safeUrl(input.url),input.notes?.trim().slice(0,3000)??null]);return resourceId;}
  async getResource(guildId:string,resourceId:string){return (await this.database.requirePool().query<any>(`select * from education_resources where guild_id=$1 and resource_id=$2`,[guildId,resourceId])).rows[0] ?? null;}
  async reviewResource(input:{guildId:string;resourceId:string;reviewerUserId:string;decision:'PUBLISHED'|'REJECTED'}){const result=await this.database.requirePool().query(`update education_resources set status=$3,reviewer_user_id=$4,updated_at=now() where guild_id=$1 and resource_id=$2 and status='REVIEW'`,[input.guildId,input.resourceId,input.decision,input.reviewerUserId]);if(!result.rowCount)throw new Error('EDUCATION_RESOURCE_NOT_REVIEWABLE');}
  async listPublished(guildId:string,limit=25){return (await this.database.requirePool().query<any>(`select resource_id,subject,title,url,notes,updated_at from education_resources where guild_id=$1 and status='PUBLISHED' order by updated_at desc limit $2`,[guildId,Math.max(1,Math.min(50,limit))])).rows;}
  async createMentorRequest(input:{guildId:string;requesterUserId:string;subject:string;goal:string;availability?:string}){if(input.subject.trim().length<2||input.goal.trim().length<10)throw new Error('MENTOR_REQUEST_INVALID');const mentorRequestId=randomUUID();await this.database.requirePool().query(`insert into mentor_requests(mentor_request_id,guild_id,requester_user_id,subject,goal,availability,status) values($1,$2,$3,$4,$5,$6,'OPEN')`,[mentorRequestId,input.guildId,input.requesterUserId,input.subject.trim().slice(0,100),input.goal.trim().slice(0,2000),input.availability?.trim().slice(0,500)??null]);return mentorRequestId;}
  async getMentorRequest(guildId:string,requestId:string){return (await this.database.requirePool().query<any>(`select * from mentor_requests where guild_id=$1 and mentor_request_id=$2`,[guildId,requestId])).rows[0]??null;}
  async claimMentorRequest(input:{guildId:string;requestId:string;mentorUserId:string}){const result=await this.database.requirePool().query(`update mentor_requests set status='CLAIMED',mentor_user_id=$3,updated_at=now() where guild_id=$1 and mentor_request_id=$2 and status='OPEN'`,[input.guildId,input.requestId,input.mentorUserId]);if(!result.rowCount)throw new Error('MENTOR_REQUEST_NOT_CLAIMABLE');}
  async scheduleMentorRequest(input:{guildId:string;requestId:string;scheduledAt:Date;timezone:string}){if(!Number.isFinite(input.scheduledAt.getTime()))throw new Error('MENTOR_SCHEDULE_INVALID');try{new Intl.DateTimeFormat('en',{timeZone:input.timezone});}catch{throw new Error('MENTOR_TIMEZONE_INVALID');}const result=await this.database.requirePool().query(`update mentor_requests set status='SCHEDULED',scheduled_at=$3,timezone=$4,updated_at=now() where guild_id=$1 and mentor_request_id=$2 and status='CLAIMED' and mentor_user_id is not null returning mentor_request_id,mentor_user_id,requester_user_id,scheduled_at,timezone`,[input.guildId,input.requestId,input.scheduledAt,input.timezone]);if(!result.rowCount)throw new Error('MENTOR_REQUEST_NOT_SCHEDULABLE');return result.rows[0];}
  async cancelMentorSchedule(input:{guildId:string;requestId:string}){const result=await this.database.requirePool().query(`update mentor_requests set status='CLAIMED',scheduled_at=null,timezone=null,updated_at=now() where guild_id=$1 and mentor_request_id=$2 and status='SCHEDULED' returning mentor_request_id`,[input.guildId,input.requestId]);return Boolean(result.rowCount);}
  async completeMentorRequest(input:{guildId:string;requestId:string;actorUserId:string;manager?:boolean}){const result=await this.database.requirePool().query(`update mentor_requests set status='COMPLETED',completed_at=now(),updated_at=now() where guild_id=$1 and mentor_request_id=$2 and status='SCHEDULED' and ($4::boolean or mentor_user_id=$3)`,[input.guildId,input.requestId,input.actorUserId,Boolean(input.manager)]);if(!result.rowCount)throw new Error('MENTOR_REQUEST_NOT_COMPLETABLE');}
}
