import { createHash, randomUUID } from 'node:crypto';
import type { Database } from '@autoserver/database';

const forbidden=/(entry\s*fee|pay\s*to\s*enter|purchase\s*required|wager|betting?|casino|slot|บาคาร่า|พนัน|เดิมพัน|ซื้อสิทธิ์)/i;
export function assertFreeEntryGiveaway(input:{title:string;prizeDescription:string;winnerCount:number;closesAt:Date}){
  if(forbidden.test(`${input.title}\n${input.prizeDescription}`))throw new Error('GIVEAWAY_GAMBLING_OR_PAID_ENTRY_FORBIDDEN');
  if(input.title.trim().length<3||input.title.trim().length>120)throw new Error('GIVEAWAY_TITLE_INVALID');
  if(input.prizeDescription.trim().length<2||input.prizeDescription.trim().length>1000)throw new Error('GIVEAWAY_PRIZE_INVALID');
  if(!Number.isInteger(input.winnerCount)||input.winnerCount<1||input.winnerCount>20)throw new Error('GIVEAWAY_WINNER_COUNT_INVALID');
  const remaining=input.closesAt.getTime()-Date.now();if(!Number.isFinite(remaining)||remaining<10*60_000||remaining>30*86_400_000)throw new Error('GIVEAWAY_DURATION_OUT_OF_RANGE');
}
export function giveawayEntrantHash(userIds:readonly string[]):string{return createHash('sha256').update([...new Set(userIds)].sort().join('\n')).digest('hex');}
export function selectGiveawayWinners(userIds:readonly string[],winnerCount:number,seed:string):string[]{
  const entrants=[...new Set(userIds)].sort();if(!entrants.length)return[];return entrants.map((userId)=>({userId,score:createHash('sha256').update(`${seed}:${userId}`).digest('hex')})).sort((a,b)=>a.score.localeCompare(b.score)||a.userId.localeCompare(b.userId)).slice(0,Math.min(winnerCount,entrants.length)).map((item)=>item.userId);
}
export class GiveawayRepository{
  constructor(private readonly database:Database){}
  async create(input:{guildId:string;channelId:string;title:string;prizeDescription:string;winnerCount:number;closesAt:Date;createdBy:string}){assertFreeEntryGiveaway(input);const giveawayId=randomUUID();await this.database.requirePool().query(`insert into giveaways(giveaway_id,guild_id,channel_id,title,prize_description,winner_count,free_entry,status,closes_at,created_by) values($1,$2,$3,$4,$5,$6,true,'OPEN',$7,$8)`,[giveawayId,input.guildId,input.channelId,input.title.trim(),input.prizeDescription.trim(),input.winnerCount,input.closesAt,input.createdBy]);return giveawayId;}
  async attachMessage(guildId:string,giveawayId:string,messageId:string){await this.database.requirePool().query(`update giveaways set message_id=$3,updated_at=now() where guild_id=$1 and giveaway_id=$2`,[guildId,giveawayId,messageId]);}
  async enter(guildId:string,giveawayId:string,userId:string):Promise<{entered:boolean;count:number}>{return this.database.transaction(async(client)=>{const giveaway=(await client.query<any>(`select status,closes_at from giveaways where guild_id=$1 and giveaway_id=$2 for share`,[guildId,giveawayId])).rows[0];if(!giveaway)throw new Error('GIVEAWAY_NOT_FOUND');if(giveaway.status!=='OPEN'||new Date(giveaway.closes_at).getTime()<=Date.now())throw new Error('GIVEAWAY_CLOSED');const result=await client.query(`insert into giveaway_entries(giveaway_id,guild_id,user_id) values($1,$2,$3) on conflict do nothing`,[giveawayId,guildId,userId]);const count=Number((await client.query<{count:string}>(`select count(*)::text as count from giveaway_entries where giveaway_id=$1`,[giveawayId])).rows[0]?.count??0);return{entered:(result.rowCount??0)>0,count};});}
  async draw(input:{guildId:string;giveawayId:string;drawnBy:string;reason?:string;allowReroll?:boolean}){return this.database.transaction(async(client)=>{const row=(await client.query<any>(`select * from giveaways where guild_id=$1 and giveaway_id=$2 for update`,[input.guildId,input.giveawayId])).rows[0];if(!row)throw new Error('GIVEAWAY_NOT_FOUND');if(row.status==='CANCELLED')throw new Error('GIVEAWAY_CANCELLED');if(new Date(row.closes_at).getTime()>Date.now())throw new Error('GIVEAWAY_STILL_OPEN');if(row.status==='DRAWN'&&!input.allowReroll)throw new Error('GIVEAWAY_ALREADY_DRAWN');const entrants=(await client.query<{user_id:string}>(`select user_id from giveaway_entries where giveaway_id=$1 order by user_id`,[input.giveawayId])).rows.map((item)=>item.user_id);if(!entrants.length)throw new Error('GIVEAWAY_HAS_NO_ENTRANTS');const drawNo=Number(row.last_draw_no)+1;const seed=randomUUID();const entrantSnapshotHash=giveawayEntrantHash(entrants);const winners=selectGiveawayWinners(entrants,Number(row.winner_count),seed);await client.query(`insert into giveaway_draws(draw_id,giveaway_id,guild_id,draw_no,seed,entrant_snapshot_hash,winner_user_ids,reason,drawn_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[randomUUID(),input.giveawayId,input.guildId,drawNo,seed,entrantSnapshotHash,winners,input.reason??null,input.drawnBy]);await client.query(`update giveaways set status='DRAWN',last_draw_no=$3,last_draw_seed=$4,entrant_snapshot_hash=$5,winner_user_ids=$6,updated_at=now() where guild_id=$1 and giveaway_id=$2`,[input.guildId,input.giveawayId,drawNo,seed,entrantSnapshotHash,winners]);return{drawNo,seed,entrantSnapshotHash,winners,entrantCount:entrants.length};});}
  async closeExpired(guildId:string,giveawayId:string):Promise<{closed:boolean;title?:string;channelId?:string;messageId?:string}>{const {rows}=await this.database.requirePool().query<any>(`update giveaways set status='CLOSED',updated_at=now() where guild_id=$1 and giveaway_id=$2 and status='OPEN' and closes_at<=now() returning title,channel_id,message_id`,[guildId,giveawayId]);const row=rows[0];return row?{closed:true,title:row.title,channelId:row.channel_id,messageId:row.message_id??undefined}:{closed:false};}
  async listOpen(guildId:string,limit=20){const {rows}=await this.database.requirePool().query<any>(`select giveaway_id,title,prize_description,winner_count,closes_at,status,(select count(*)::int from giveaway_entries e where e.giveaway_id=g.giveaway_id) as entry_count from giveaways g where guild_id=$1 and status='OPEN' and closes_at>now() order by closes_at asc limit $2`,[guildId,Math.max(1,Math.min(50,limit))]);return rows;}
}
