const exact:Record<string,string>={
  ok:'ปกติ',healthy:'ปกติ',ready:'พร้อม',unknown:'ไม่ทราบ',online:'ออนไลน์',offline:'ออฟไลน์',degraded:'ประสิทธิภาพลดลง',unavailable:'ไม่พร้อมใช้งาน',
  RUNNING:'กำลังทำงาน',QUEUED:'รอคิว',RETRYING:'กำลังลองใหม่',SUCCEEDED:'สำเร็จ',SUCCESS:'สำเร็จ',FAILED:'ล้มเหลว',REJECTED:'ถูกปฏิเสธ',CANCELLED:'ยกเลิกแล้ว',COMPLETED:'เสร็จสิ้น',CAPTURED:'บันทึกชุดสำรองแล้ว',INTEGRITY_CHECKED:'ตรวจความสมบูรณ์แล้ว',RESTORE_VERIFIED:'ยืนยันการกู้คืนแล้ว',INVALID:'ไม่ผ่านการตรวจ',LEGACY_UNPROVEN:'ข้อมูลเดิมยังไม่มีหลักฐานยืนยัน',
  CREATE:'สร้าง',UPDATE:'อัปเดต',ADOPT:'รับดูแล',KEEP:'คงไว้',SKIP:'ข้าม',CONFLICT:'ขัดแย้ง',DELETE:'ลบ',RETIRE:'เลิกใช้',
  CATEGORY:'หมวดหมู่',ROLE:'ยศ',TEXT_CHANNEL:'ช่องข้อความ',FORUM_CHANNEL:'ฟอรัม',VOICE_CHANNEL:'ช่องเสียง',
  PUBLIC:'สาธารณะ',VERIFIED:'สมาชิกที่ยืนยันแล้ว',VERIFIED_ONLY:'สมาชิกที่ยืนยันแล้ว',NEW_MEMBER:'สมาชิกใหม่',STAFF:'ทีมงาน',EVENT:'กิจกรรม',BOT:'บอต',ARCHIVE:'คลังเก็บ',
  STATIC:'นิ่ง',BALANCED:'สมดุล',ANIMATED:'เคลื่อนไหว',CINEMATIC:'ภาพยนตร์',COMPACT:'กะทัดรัด',COMFORTABLE:'สบายตา',SPACIOUS:'โปร่ง',CLEAN:'เรียบ',SIGNAL:'มีสัญญาณ',ICONIC:'มีสัญลักษณ์',CLASSIC:'คลาสสิก',THEMED:'ตามธีม',ENHANCED:'เสริมมิติ',MINIMAL:'น้อย',RICH:'เต็ม',
  OFF:'ปิด',ON:'เปิด',DAILY:'รายวัน',WEEKLY:'รายสัปดาห์',INHERIT:'สืบทอด',OBSERVE:'เฝ้าดู',ENFORCE:'บังคับใช้',STRICT:'เข้มงวด',ENTERPRISE:'องค์กร',
  NONE:'ไม่มี',FULL:'เต็ม',TAIL:'ช่วงท้าย',HEALTHY:'สมบูรณ์',DEGRADED:'ผิดปกติ',UNINITIALIZED:'ยังไม่เริ่ม',CHAINED:'เชื่อมสายหลักฐาน',LEGACY_UNCHAINED:'ข้อมูลเดิมก่อนระบบสายหลักฐาน','durable-state':'สถานะถาวร',
  SMALL:'ขนาดเล็ก',LARGE:'ขนาดใหญ่',WATCH:'เฝ้าระวัง',THROTTLE:'จำกัดงาน',EMERGENCY:'ฉุกเฉิน',RECOMMEND:'แนะนำ',OPTIONAL:'เลือกใช้ได้',OMIT:'ไม่แนะนำ',
  INSUFFICIENT_DATA:'ข้อมูลยังไม่พอ',REVIEW_EXPAND:'ทบทวนเพื่อขยาย',REVIEW_HOLD:'คงสถานะและทบทวน',REVIEW_ROLLBACK:'ทบทวนเพื่อย้อนกลับ',
  NO_MATCHING_ROLLOUT:'ไม่พบกฎการทยอยเปิดใช้ที่ตรงกัน',GLOBAL_OFF:'ปิดจากกฎส่วนกลาง',GLOBAL_ON:'เปิดจากกฎส่วนกลาง',GUILD_OFF:'ปิดสำหรับเซิร์ฟเวอร์นี้',GUILD_ON:'เปิดสำหรับเซิร์ฟเวอร์นี้',ENVIRONMENT_OFF:'ปิดสำหรับสภาพแวดล้อมนี้',ENVIRONMENT_ON:'เปิดสำหรับสภาพแวดล้อมนี้',ROLE_OFF:'ปิดสำหรับยศนี้',ROLE_ON:'เปิดสำหรับยศนี้',CANARY_INCLUDED:'อยู่ในกลุ่มทยอยเปิดใช้',CANARY_EXCLUDED:'อยู่นอกกลุ่มทยอยเปิดใช้',
  memberCount:'สมาชิก',roleCount:'ยศ',channelCount:'ช่อง',activeTickets7d:'คำขอช่วยเหลือ 7 วัน',events30d:'กิจกรรม 30 วัน',lfg30d:'กลุ่มหาเพื่อนเล่น 30 วัน',staffCount:'ทีมงาน',
};
const modules:Record<string,string>={
  setup:'ตั้งค่าระบบ',scanner:'สแกนโครงสร้าง',planner:'วางแผน',blueprints:'แม่แบบเซิร์ฟเวอร์',permissions:'สิทธิ์',panels:'แผงควบคุม',forums:'ฟอรัม','asset-fabric':'คลังสื่อ','visual-experience':'ระบบภาพ','digital-twin':'ฝาแฝดจำลองเซิร์ฟเวอร์','operations-intelligence':'ข่าวกรองปฏิบัติการ','event-replay':'เล่นเหตุการณ์ย้อนหลัง',onboarding:'เริ่มต้นสมาชิก',verification:'ยืนยันตัวตน',roles:'ยศ',notifications:'การแจ้งเตือน','community-programs':'โครงการชุมชน',knowledge:'คลังความรู้','member-services':'บริการสมาชิก',partnerships:'พันธมิตร',accessibility:'การเข้าถึง',localization:'ภาษา',discovery:'การค้นพบ','member-care':'ดูแลสมาชิก',tickets:'ศูนย์ช่วยเหลือ',applications:'ใบสมัคร',suggestions:'ข้อเสนอแนะ',reports:'รายงาน',moderation:'ดูแลชุมชน',security:'ความปลอดภัย','trust-safety':'ความน่าเชื่อถือและความปลอดภัย',approvals:'การอนุมัติ',privacy:'ความเป็นส่วนตัว',retention:'การเก็บข้อมูล',events:'กิจกรรม','event-studio':'สตูดิโอกิจกรรม',giveaways:'รางวัลเข้าร่วมฟรี',scheduler:'กำหนดเวลา',automation:'ระบบอัตโนมัติ',voice:'ระบบเสียง',maintenance:'บำรุงรักษา','change-control':'ควบคุมการเปลี่ยนแปลง','release-ops':'งานเผยแพร่',realtime:'ข้อมูลสด',assets:'สื่อ',integrations:'การเชื่อมต่อ',backup:'สำรองข้อมูล',repair:'ซ่อมแซม',diagnostics:'วินิจฉัย',analytics:'วิเคราะห์ข้อมูล','data-observatory':'หอดูข้อมูล',recommendations:'คำแนะนำ','feature-flags':'สวิตช์ฟีเจอร์','reliability-ops':'ความน่าเชื่อถือ',gaming:'ระบบเกม',lfg:'หากลุ่มเล่น',teams:'ทีม',clans:'แคลน',tournaments:'การแข่งขัน',creator:'ครีเอเตอร์',education:'การเรียนรู้',business:'ธุรกิจ','project-lab':'ห้องโครงการ','content-studio':'สตูดิโอเนื้อหา','knowledge-ops':'ดูแลความรู้','member-ops':'งานสมาชิก',plugins:'ส่วนเสริม','ai-hooks':'การเชื่อม AI',
  party:'ปาร์ตี้',recruitment:'รับสมาชิก',scrims:'สคริม',matches:'แมตช์',xp:'ค่าประสบการณ์',quests:'ภารกิจ',achievements:'ความสำเร็จ','seasonal-progression':'ความก้าวหน้าตามฤดูกาล',guides:'คู่มือ',clips:'คลิป',coaching:'โค้ช','game-registry':'ทะเบียนเกม',profiles:'โปรไฟล์','news-status-adapters':'ข่าวและสถานะเกม',
  platform:'แพลตฟอร์ม',discord:'Discord','job-worker':'ตัวทำงานคิว',outbox:'ขาออกเหตุการณ์',inbox:'ขาเข้าเหตุการณ์','living-panels':'แผงข้อมูลสด',worker:'ตัวทำงาน',api:'API',all:'ทุกบทบาท',
};
const eventLabels:Record<string,string>={
  'member.join':'สมาชิกเข้าร่วม','verification.succeeded':'ยืนยันสมาชิกสำเร็จ','ticket.created':'สร้างคำขอช่วยเหลือ','ticket.closed':'ปิดคำขอช่วยเหลือ','security.alert':'แจ้งเตือนความปลอดภัย','gaming.xp.awarded':'ได้รับค่าประสบการณ์','gaming.level.up':'เลเวลเพิ่มขึ้น','community.event.created':'สร้างกิจกรรม','community.event.registered':'ลงทะเบียนกิจกรรม','community.event.checkin':'เช็กอินกิจกรรม','setup.job.started':'เริ่มงานตั้งค่า','setup.job.completed':'งานตั้งค่าเสร็จสิ้น','restore.job.started':'เริ่มกู้คืน','restore.job.completed':'กู้คืนเสร็จสิ้น','maintenance.activated':'เริ่มบำรุงรักษา','maintenance.completed':'บำรุงรักษาเสร็จสิ้น',
};
export function thValue(value:unknown):string{const key=String(value??'');return exact[key]??modules[key]??key;}
export function thModule(value:string):string{return modules[value]??value;}
export function thEventType(value:string):string{return eventLabels[value]??value.split('.').map((part)=>modules[part]??exact[part.toUpperCase()]??part).join(' · ');}
export function thBoolean(value:unknown):string{return value===true?'ใช่':value===false?'ไม่ใช่':'ไม่ทราบ';}

const fields:Record<string,string>={
  id:'รหัส',kind:'ชนิด',status:'สถานะ',name:'ชื่อ',title:'ชื่อเรื่อง',module:'โมดูล',source:'แหล่งข้อมูล',enabled:'เปิดใช้',version:'รุ่น',reason:'เหตุผล',created_at:'สร้างเมื่อ',updated_at:'อัปเดตเมื่อ',started_at:'เริ่มเมื่อ',completed_at:'เสร็จเมื่อ',expires_at:'หมดอายุเมื่อ',next_at:'กำหนดครั้งถัดไป',last_run_at:'ทำงานล่าสุด',run_at:'กำหนดทำงาน',
  guild_id:'รหัสเซิร์ฟเวอร์',user_id:'รหัสสมาชิก',actor_id:'รหัสผู้ดำเนินการ',panel_id:'รหัสแผง',logical_key:'คีย์เชิงตรรกะ',discord_id:'รหัสดิสคอร์ด',resource_type:'ชนิดทรัพยากร',resource_id:'รหัสทรัพยากร',channel_id:'รหัสช่อง',role_id:'รหัสยศ',event_type:'ชนิดเหตุการณ์',rule_key:'คีย์กฎ',budget_key:'คีย์งบ',integration_key:'คีย์การเชื่อมต่อ',
  count:'จำนวน',total:'รวม',healthy:'ปกติ',open:'เปิดอยู่',failed:'ล้มเหลว',running:'กำลังทำงาน',queued:'รอคิว',completed:'เสร็จสิ้น',active:'ใช้งาน',configured:'ตั้งค่าแล้ว',cancellable:'ยกเลิกได้',preset:'ชุดค่า',mode:'โหมด',window_seconds:'ช่วงเวลา (วินาที)',max_units:'หน่วยสูงสุด',fail_closed_when_unknown:'ปิดแบบปลอดภัยเมื่อไม่ทราบ',
  checks_passed:'รายการตรวจผ่าน',checks_failed:'รายการตรวจล้มเหลว',artifact_refs:'ข้อมูลอ้างอิงหลักฐาน',blockers:'ตัวขัดขวาง',conditions:'เงื่อนไข',actions:'การดำเนินการ',config:'การตั้งค่า',capabilities:'ความสามารถ',locale:'ภาษา',owner:'เจ้าของ',repo:'คลัง',include_prereleases:'รวมรุ่นก่อนเผยแพร่',
};
export function thField(value:string):string{return fields[value]??value.split('_').map((part)=>modules[part]??exact[part.toUpperCase()]??part).join(' ');}
