import { createHash, randomUUID } from 'node:crypto';
import type { Database } from '@autoserver/database';

function safeUrl(value?:string){if(!value)return undefined;const u=new URL(value);if(!['https:','http:'].includes(u.protocol))throw new Error('BUSINESS_URL_PROTOCOL_INVALID');return u.toString();}
function normalizeKey(value:string){const key=value.trim().toUpperCase().replace(/[^A-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,60);if(!key)throw new Error('BUSINESS_ITEM_KEY_INVALID');return key;}
function rejectPaymentCredentialLike(text:string){if(/(?:\d[ -]*?){13,19}/.test(text)||/\b(?:cvv|cvc|security code)\b/i.test(text))throw new Error('PAYMENT_CREDENTIALS_NOT_ALLOWED');}
export class BusinessRepository{
  constructor(private readonly database:Database){}
  async upsertCatalogItem(input:{guildId:string;createdBy:string;itemKey:string;name:string;description:string;publicUrl?:string;status?:'DRAFT'|'ACTIVE'}){rejectPaymentCredentialLike(`${input.name} ${input.description}`);const itemId=randomUUID();const key=normalizeKey(input.itemKey);await this.database.requirePool().query(`insert into business_catalog_items(item_id,guild_id,item_key,name,description,public_url,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(guild_id,item_key) do update set name=excluded.name,description=excluded.description,public_url=excluded.public_url,status=excluded.status,updated_at=now()`,[itemId,input.guildId,key,input.name.trim().slice(0,120),input.description.trim().slice(0,2000),safeUrl(input.publicUrl),input.status??'ACTIVE',input.createdBy]);return key;}
  async listActive(guildId:string,limit=25){return (await this.database.requirePool().query<any>(`select item_key,name,description,public_url from business_catalog_items where guild_id=$1 and status='ACTIVE' order by updated_at desc limit $2`,[guildId,Math.max(1,Math.min(50,limit))])).rows;}
  async createSupportReference(input:{guildId:string;userId:string;externalReference?:string;issue:string;priority?:'LOW'|'NORMAL'|'HIGH'|'URGENT';slaHours?:number}){rejectPaymentCredentialLike(`${input.externalReference??''} ${input.issue}`);const raw=input.externalReference?.trim();const supportRefId=randomUUID();const hash=raw?createHash('sha256').update(raw).digest('hex'):undefined;const masked=raw?`${raw.slice(0,2)}…${raw.slice(-2)}`:undefined;const priority=input.priority??'NORMAL';const slaHours=Math.max(1,Math.min(168,Math.trunc(input.slaHours??24)));const due=new Date(Date.now()+slaHours*60*60_000);await this.database.requirePool().query(`insert into business_support_refs(support_ref_id,guild_id,requester_user_id,external_ref_hash,external_ref_masked,issue,status,priority,sla_due_at) values($1,$2,$3,$4,$5,$6,'OPEN',$7,$8)`,[supportRefId,input.guildId,input.userId,hash??null,masked??null,input.issue.trim().slice(0,3000),priority,due]);return {supportRefId,masked,slaDueAt:due};}
  async listOpenSupport(guildId:string,limit=25){return (await this.database.requirePool().query<any>(`select support_ref_id,requester_user_id,external_ref_masked,issue,status,priority,sla_due_at,assigned_staff_id,created_at from business_support_refs where guild_id=$1 and status in ('OPEN','CLAIMED') order by case priority when 'URGENT' then 0 when 'HIGH' then 1 when 'NORMAL' then 2 else 3 end,sla_due_at nulls last,created_at asc limit $2`,[guildId,Math.max(1,Math.min(50,limit))])).rows;}
  async claimSupport(input:{guildId:string;supportRefId:string;staffId:string}){const result=await this.database.requirePool().query(`update business_support_refs set status='CLAIMED',assigned_staff_id=$3,claimed_at=now(),updated_at=now() where guild_id=$1 and support_ref_id=$2 and status='OPEN'`,[input.guildId,input.supportRefId,input.staffId]);if(!result.rowCount)throw new Error('BUSINESS_SUPPORT_NOT_CLAIMABLE');}
  async resolveSupport(input:{guildId:string;supportRefId:string;staffId:string;next:'RESOLVED'|'CLOSED'}){const result=await this.database.requirePool().query(`update business_support_refs set status=$4,assigned_staff_id=coalesce(assigned_staff_id,$3),resolved_at=case when $4='RESOLVED' then now() else resolved_at end,updated_at=now() where guild_id=$1 and support_ref_id=$2 and status in ('OPEN','CLAIMED','RESOLVED') and (assigned_staff_id is null or assigned_staff_id=$3 or $4='CLOSED')`,[input.guildId,input.supportRefId,input.staffId,input.next]);if(!result.rowCount)throw new Error('BUSINESS_SUPPORT_NOT_RESOLVABLE');}
}
