import { createHmac } from 'node:crypto';
import assert from 'node:assert/strict';
import { stableRolloutBucket, evaluateFeatureRollouts, rolloutIdentityHash, reviewCanaryOutcome } from '../packages/feature-flags/src/index.ts';
import { containsSecretLikeData, validateAiHookRequest, createOpenAiResponsesProvider, createRuleBasedAdvisorProvider, parseAiCapabilityAllowlist, parseAiDataClassAllowlist } from '../packages/ai-hooks/src/index.ts';
import { assertFreeEntryGiveaway, giveawayEntrantHash, selectGiveawayWinners } from '../packages/giveaways/src/index.ts';
import { decideEventSequence } from '../packages/core/src/index.ts';
import { assessGrowth, scoreChannelRecommendation } from '../packages/growth/src/index.ts';
import { validateMaintenanceWindow } from '../packages/operations/src/index.ts';
import { generateBlueprintTree, generateServerBlueprintReport } from '../packages/documentation/src/index.ts';
import { InProcessTtlCache, LayeredCache } from '../packages/cache/src/index.ts';
import { validateRecruitmentPost } from '../packages/gaming/src/recruitment.ts';
import { createPortableConfig, migratePortableConfig, validatePortableConfig } from '../packages/governance/src/portable-config.ts';
import { transitionApplication } from '../packages/workflows/src/index.ts';
import { isTaskDue, parseScheduleInstant } from '../packages/scheduler/src/index.ts';
import { mutationRateLimitPolicy, rateLimitSubjectHash, evaluateFixedWindow, securityHeaders } from '../packages/http-security/src/index.ts';
import { transitionCreatorContent } from '../packages/creator/src/index.ts';
import { sanitizeIntegrationHealthDetail, CircuitBreaker, validateIntegrationSecretRef, validateWebhookDeliveryId, validateWebhookTimestamp, webhookDigest, createGenericInboundAdapter, createRiotDataDragonAdapter, createGitHubReleasesAdapter, createDiscordStatusAdapter, integrationPayloadHash, assertPublicIntegrationConfigSafe } from '../packages/integrations/src/index.ts';
import { redactAuditValue, encodeAuditCursor, decodeAuditCursor } from '../packages/audit-log/src/index.ts';
import { buildReleaseTruth } from '../packages/release-truth/src/index.ts';
import { defaultSetupDraft, normalizeSetupDraft } from '../packages/control-center/src/index.ts';
import { localizationCoverage } from '../packages/localization/src/index.ts';
import { defaultFabricVisibility, fabricStatusIsPublic, transitionFabricStatus, validateFabricSubmission } from '../packages/community-fabric/src/index.ts';
import { transitionIncidentStatus, validateIncidentCreate } from '../packages/incidents/src/index.ts';
import { assessCapacity } from '../packages/capacity/src/index.ts';
import { transitionRecoveryDrill, validateRecoveryDrillPlan } from '../packages/recovery-drills/src/index.ts';
import { budgetWindowStart, defaultBudgetPolicy, previewBudgetDecision, validateBudgetKey, RESOURCE_BUDGET_KEYS } from '../packages/budgets/src/index.ts';
import { compareJobFairness, jobPriorityBand } from '../packages/jobs/src/fairness.ts';
import { matchAutomationRule, validateAutomationAction, validateAutomationRuleDefinition } from '../packages/automation/src/index.ts';
import { defaultAdmissionPolicy, evaluateAdmission } from '../packages/admission-control/src/pure.ts';
let n=0;const ok=(value,msg)=>{assert.ok(value,msg);n+=1;};
ok(stableRolloutBucket('x','u')===stableRolloutBucket('x','u'),'stable rollout');
const outcomeComparison={guildId:'g',featureKey:'x',metricKey:'success.rate',lookbackDays:14,enabled:{samples:30,average:0.84,sum:25.2,min:0,max:1},excluded:{samples:30,average:0.70,sum:21,min:0,max:1}};ok(reviewCanaryOutcome({comparison:outcomeComparison,minimumRelativeLift:0.05}).action==='REVIEW_EXPAND','canary outcome review is advisory');ok(reviewCanaryOutcome({comparison:{...outcomeComparison,enabled:{...outcomeComparison.enabled,samples:2}}}).action==='INSUFFICIENT_DATA','canary outcome review requires evidence');
const flag=evaluateFeatureRollouts('x',[{rolloutId:'g',featureKey:'x',scope:'GUILD',guildId:'g',state:'ON',rolloutPercent:100,config:{}}],{guildId:'g',environment:'test'});ok(flag.enabled,'guild flag');
ok(containsSecretLikeData({nested:{service_role:'x'}})==='root.nested.service_role','secret path');
let rejected=false;try{validateAiHookRequest({guildId:'g',capability:'AUDIT_SUMMARY',input:{token:'x'},inputClasses:['AUDIT'],correlationId:'c'});}catch{rejected=true;}ok(rejected,'AI secret rejection');
const provider=createRuleBasedAdvisorProvider();const response=await provider.execute({guildId:'g',capability:'ANALYTICS_SUMMARY',input:{tickets:2},inputClasses:['ANALYTICS'],correlationId:'c'},new AbortController().signal);ok(provider.freeByDefault&&response.summary.includes('tickets: 2'),'local advisor');
ok(parseAiCapabilityAllowlist('AUDIT_SUMMARY,ANALYTICS_SUMMARY').length===2,'external AI capability allowlist');
rejected=false;try{parseAiDataClassAllowlist('PUBLIC,SECRET');}catch{rejected=true;}ok(rejected,'external AI secret class cannot be allowed');
let aiExternalBody;const externalAi=createOpenAiResponsesProvider({apiKey:'smoke-secret',model:'gpt-smoke-fixed',allowedCapabilities:['AUDIT_SUMMARY'],allowedDataClasses:['AUDIT'],fetchImpl:async(_url,init)=>{aiExternalBody=JSON.parse(String(init?.body));return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'external smoke'}]}]}),{status:200});}});const externalAiResult=await externalAi.execute({guildId:'g',actorId:'admin',capability:'AUDIT_SUMMARY',input:{events:3},inputClasses:['AUDIT'],correlationId:'c-ai'},new AbortController().signal);ok(externalAi.egress==='EXTERNAL'&&aiExternalBody.store===false&&externalAiResult.summary==='external smoke','external AI fixed egress/store false contract');
rejected=false;try{assertFreeEntryGiveaway({title:'Community reward',prizeDescription:'pay to enter',winnerCount:1,closesAt:new Date(Date.now()+3_600_000)});}catch{rejected=true;}ok(rejected,'paid entry rejected');
ok(giveawayEntrantHash(['u2','u1','u1'])===giveawayEntrantHash(['u1','u2']),'entrant hash dedup');
ok(JSON.stringify(selectGiveawayWinners(['u3','u1','u2'],2,'seed'))===JSON.stringify(selectGiveawayWinners(['u2','u1','u3'],2,'seed')),'deterministic draw');
ok(decideEventSequence({sequence:7,eventId:'a'},{sequence:6,eventId:'b'}).stale,'stale event ordering');
ok(decideEventSequence({sequence:7,eventId:'a'},{sequence:7,eventId:'a'}).duplicate,'duplicate event ordering');
ok(decideEventSequence({sequence:7,eventId:'a'},{sequence:8,eventId:'b'}).accepted,'monotonic event ordering');
const growth=assessGrowth({memberCount:9000,roleCount:55,channelCount:110,activeTickets7d:75,events30d:12,lfg30d:240});ok(['LARGE','ENTERPRISE'].includes(growth.mode)&&['advanced','enterprise'].includes(growth.recommendedComplexity),'growth mode');
ok(scoreChannelRecommendation({key:'unused',purpose:'duplicate',expectedWeeklyUse:0,audienceCoverage:.03,moderationCost:1,duplicateRisk:1}).recommendation==='OMIT','channel recommendation');
const start=new Date(Date.now()+60_000);ok(validateMaintenanceWindow({startsAt:start,endsAt:new Date(start.getTime()+3600_000)}).startsAt===start,'maintenance validation');
const blueprint={key:'smoke',version:1,displayName:'Smoke',description:'Smoke blueprint',complexity:'compact',enabledModules:['core'],resources:[{logicalKey:'CAT_START',kind:'CATEGORY',name:'START',ownership:'SYSTEM_OWNED',reason:'smoke',module:'core'},{logicalKey:'CH_WELCOME',kind:'TEXT_CHANNEL',name:'welcome',parentKey:'CAT_START',ownership:'SYSTEM_OWNED',reason:'smoke',module:'core',visibility:'PUBLIC'}]};
ok(generateBlueprintTree(blueprint).includes('CH_WELCOME'),'blueprint tree');ok(generateServerBlueprintReport({blueprint,panelIds:['PANEL_WELCOME']}).includes('PANEL_WELCOME'),'blueprint report');
const recruitment=validateRecruitmentPost({gameKey:'valorant',postType:'TEAM_RECRUITING',title:'Need controller',preferredRoles:['Controller','Controller'],expiresAt:new Date(Date.now()+86_400_000)});ok(recruitment.preferredRoles.length===1,'gaming recruitment validation');
const l1=new InProcessTtlCache(10);const cache=new LayeredCache(l1);let loads=0;await cache.getOrLoad('smoke','key',1000,async()=>{loads+=1;return 1;});await cache.getOrLoad('smoke','key',1000,async()=>{loads+=1;return 2;});ok(loads===1,'cache ttl optimization');for(let i=0;i<15;i+=1)await l1.set({scopeKey:'bound',cacheKey:`k${i}`,value:i,ttlMs:1000});ok(l1.stats().entries<=10&&l1.stats().evictions>=5,'cache memory bound');

ok(rolloutIdentityHash({guildId:'g',userId:'member-123',environment:'test'}).length===64,'rollout identity is hashed');
const portableV1=createPortableConfig({schemaVersion:1,exportedAt:'2026-08-14T00:00:00Z',guildId:'g',payload:{setupDraft:{blueprintKey:'hybrid-standard'},templateVersion:4}});const migrated=migratePortableConfig(portableV1);ok(migrated.targetSchemaVersion===2&&migrated.appliedMigrations.length===1&&validatePortableConfig(migrated.envelope),'portable config migration');
rejected=false;try{migratePortableConfig({...portableV1,payload:{...portableV1.payload,templateVersion:999}});}catch{rejected=true;}ok(rejected,'portable config tamper rejection');
ok(!validatePortableConfig({...migrated.envelope,exportedAt:'2099-01-01T00:00:00Z'}),'portable v2 timestamp tamper rejection');
ok(transitionApplication('SUBMITTED','UNDER_REVIEW')==='UNDER_REVIEW','workflow transition contract');
ok(!isTaskDue({taskId:'t',guildId:'g',runAt:new Date(0),state:'CANCELLED',dedupKey:'d'},new Date()),'cancelled scheduled task is never due');
ok(!sanitizeIntegrationHealthDetail('token=super-secret-value').includes('super-secret-value'),'integration health detail redaction');
const scheduled=parseScheduleInstant('2026-08-20T19:00:00+07:00',new Date('2026-08-14T00:00:00Z'));ok(scheduled.getTime()>Date.parse('2026-08-14T00:00:00Z'),'future schedule parsing');
rejected=false;try{parseScheduleInstant('2026-08-13T00:00:00Z',new Date('2026-08-14T00:00:00Z'));}catch{rejected=true;}ok(rejected,'past schedule rejection');
ok(transitionCreatorContent('REVIEW','APPROVED')==='APPROVED','creator review transition');
ok(mutationRateLimitPolicy('/api/guilds/g/restore/run').limit===30,'high-risk mutation rate limit');
ok(rateLimitSubjectHash({actorId:'user-1',guildId:'g',routeClass:'restore'}).length===64,'rate-limit identity hashing');
ok(!evaluateFixedWindow({count:31,limit:30,windowStart:0,windowMs:60_000}).allowed,'fixed-window rejection');
ok(securityHeaders('https://dashboard.example')['permissions-policy'].includes('payment=()'),'payment capability disabled by security headers');
const phase6Circuit=new CircuitBreaker(2,5_000); phase6Circuit.failure(1_000); phase6Circuit.failure(1_100); ok(phase6Circuit.snapshot(1_101).state==='OPEN','integration circuit opens after threshold'); ok(phase6Circuit.canAttempt(2_000)===false,'integration circuit blocks before retry'); ok(phase6Circuit.canAttempt(6_101)===true,'integration circuit admits one half-open probe'); ok(phase6Circuit.canAttempt(6_102)===false,'integration circuit blocks concurrent half-open probes'); phase6Circuit.success(); ok(phase6Circuit.snapshot(6_103).state==='CLOSED','integration circuit closes after successful probe');

const auditRedacted=redactAuditValue({token:'secret',safe:'ok',nested:{password:'hidden'}});ok(auditRedacted.safe==='ok'&&auditRedacted.token==='[redacted]'&&auditRedacted.nested.password==='[redacted]','audit recursive redaction');
const auditCursor=encodeAuditCursor({createdAt:'2026-08-14T00:00:00.000Z',auditId:'11111111-1111-4111-8111-111111111111'});ok(decodeAuditCursor(auditCursor)?.auditId.startsWith('11111111'),'audit cursor roundtrip');
ok(validateIntegrationSecretRef('news-feed','env:INTEGRATION_NEWS_FEED_WEBHOOK_SECRET').endsWith('WEBHOOK_SECRET'),'webhook env secret reference bound to adapter key');
ok(validateWebhookDeliveryId('delivery-123')==='delivery-123','webhook delivery id validation');
rejected=false;try{validateWebhookTimestamp('1000',300,2_000_000_000_000);}catch{rejected=true;}ok(rejected,'stale webhook timestamp rejected');
ok(webhookDigest('payload').length===64,'webhook payload hash');
ok(localizationCoverage().complete,'localization key parity');
const releaseTruth=buildReleaseTruth(process.cwd());ok(!releaseTruth.ready&&releaseTruth.findings.some((finding)=>finding.includes('lockfile.missing')),'release truth preserves known blocker');

const genericInbound=createGenericInboundAdapter();const genericBody=new TextEncoder().encode(JSON.stringify({eventType:'build.ready',payload:{ok:true},aggregateKey:'build:1',sequence:1}));const genericTs='1770000000';const genericSecret='this-is-a-long-generic-inbound-secret';const genericSig=createHmac('sha256',genericSecret).update(genericTs).update('.').update(genericBody).digest('hex');ok(await genericInbound.webhook.verify({rawBody:genericBody,signature:`sha256=${genericSig}`,secret:genericSecret,timestamp:genericTs,headers:{}}),'generic inbound HMAC verification');const genericEvents=await genericInbound.webhook.transform({rawBody:genericBody,headers:{}});ok(genericEvents[0]?.eventType==='integration.generic.build.ready'&&genericEvents[0]?.sequence===1,'generic inbound event namespace');

const riotMock={json:async(url)=>{if(url.endsWith('/api/versions.json'))return ['16.9.1'];const data={};for(let i=0;i<100;i+=1)data[`C${i}`]={id:`C${i}`,key:String(i),name:`Champion ${String(i).padStart(3,'0')}`,title:'test',image:{full:`C${i}.png`}};return {data};}};
const riotAdapter=createRiotDataDragonAdapter(riotMock);const riotSync=await riotAdapter.sync({config:{locale:'th_TH'}});ok(riotSync.itemCount===100&&riotSync.externalVersion==='16.9.1','Riot Data Dragon normalized sync');
const githubAdapter=createGitHubReleasesAdapter({json:async()=>[{id:1,tag_name:'v1.2.3',name:'Release',body:'Notes',html_url:'https://github.com/acme/project/releases/tag/v1.2.3',draft:false,prerelease:false,published_at:'2026-08-14T00:00:00Z'}]});const githubSync=await githubAdapter.sync({config:{owner:'acme',repo:'project'}});ok(githubSync.itemCount===1&&githubSync.externalVersion==='v1.2.3','GitHub public release normalized sync');
const discordStatusAdapter=createDiscordStatusAdapter({json:async(url)=>url.endsWith('/status.json')?{page:{updated_at:'2026-08-14T00:00:00Z'},status:{indicator:'none',description:'All Systems Operational'}}:{page:{updated_at:'2026-08-14T00:00:00Z'},status:{indicator:'minor',description:'Minor Service Outage'},components:[{id:'api',name:'API',status:'degraded_performance'}],incidents:[{id:'i1',name:'API delays',status:'monitoring',impact:'minor'}],scheduled_maintenances:[]}});const discordStatusSync=await discordStatusAdapter.sync({config:{}});ok(discordStatusSync.contentType==='discord-status'&&discordStatusSync.itemCount===2,'Discord status summary normalized sync');
const setupIntegrationDraft=normalizeSetupDraft({...defaultSetupDraft(),integrations:{riotDataDragon:{enabled:true,locale:'th_TH',syncCadence:'DAILY'},githubReleases:{enabled:true,owner:'openai',repo:'example.repo',includePrereleases:false,syncCadence:'WEEKLY'},discordStatus:{enabled:true,syncCadence:'DAILY'}}});ok(setupIntegrationDraft.integrations.riotDataDragon.enabled&&setupIntegrationDraft.integrations.githubReleases.owner==='openai'&&setupIntegrationDraft.integrations.discordStatus.enabled,'setup integration draft normalization');
const setupAiExternal=normalizeSetupDraft({...defaultSetupDraft(),aiProvider:'openai-responses'});const setupAiInvalid=normalizeSetupDraft({...defaultSetupDraft(),aiProvider:'arbitrary-external'});ok(defaultSetupDraft().aiProvider==='local-rules'&&setupAiExternal.aiProvider==='openai-responses'&&setupAiInvalid.aiProvider==='local-rules','setup AI provider is explicit opt-in with fail-safe fallback');
rejected=false;try{assertPublicIntegrationConfigSafe({apiKey:'forbidden'});}catch{rejected=true;}ok(rejected,'public integration config rejects secret-like fields');
ok(integrationPayloadHash({b:2,a:1})===integrationPayloadHash({a:1,b:2}),'integration snapshot hash is key-order stable');
ok(defaultFabricVisibility('MEMBER_CARE')==='PRIVATE'&&defaultFabricVisibility('PROJECT')==='GUILD','fabric privacy defaults');
ok(validateFabricSubmission({domain:'PROJECT',title:'Community docs',summary:'Build and review an updated community guide.',metadata:{area:'onboarding'}}).metadata.area==='onboarding','fabric submission validation');
rejected=false;try{validateFabricSubmission({domain:'CONTENT',title:'Content brief',summary:'Create a reviewed community content brief.',metadata:{apiToken:'forbidden'}});}catch{rejected=true;}ok(rejected,'fabric metadata secret-key rejection');
ok(transitionFabricStatus('OPEN','APPROVED')==='APPROVED'&&transitionFabricStatus('APPROVED','ACTIVE')==='ACTIVE','fabric workflow transitions');
ok(!fabricStatusIsPublic('OPEN')&&fabricStatusIsPublic('APPROVED'),'fabric publication gate');

ok(validateIncidentCreate({kind:'PLATFORM',severity:'HIGH',title:'Gateway saturation',summary:'Gateway operations are delayed and durable jobs are backing up.'}).severity==='HIGH','incident declaration validation');
ok(transitionIncidentStatus('OPEN','INVESTIGATING')==='INVESTIGATING','incident investigation transition');
rejected=false;try{transitionIncidentStatus('INVESTIGATING','RESOLVED','short');}catch{rejected=true;}ok(rejected,'incident resolution requires evidence note');
const normalCapacity=assessCapacity({resourceCount:120,queuedJobs:2,retryingJobs:0,deadLetterJobs:0,dueScheduledTasks:2,notificationBacklog:5,realtimeBackpressureDisconnects:0,realtimeSendFailures:0,criticalOpenIncidents:0});ok(normalCapacity.pressure==='NORMAL','capacity normal evidence');
const criticalCapacity=assessCapacity({resourceCount:430,queuedJobs:15,retryingJobs:8,deadLetterJobs:1,dueScheduledTasks:20,notificationBacklog:120,realtimeBackpressureDisconnects:2,realtimeSendFailures:2,criticalOpenIncidents:1});ok(['THROTTLE','EMERGENCY'].includes(criticalCapacity.pressure)&&criticalCapacity.score>=80,'capacity escalates critical incident/backlog evidence');

ok(validateRecoveryDrillPlan({drillType:'RESTORE',objective:'Prove backup restore and attribute verification.',expectedChecks:['Restore snapshot','Verify managed attributes']}).expectedChecks.length===2,'recovery drill plan validation');
rejected=false;try{transitionRecoveryDrill('RUNNING','PASSED',{evidence:{checksPassed:1,checksFailed:0,artifactRefs:[]}});}catch{rejected=true;}ok(rejected,'recovery drill cannot pass without evidence');
ok(transitionRecoveryDrill('RUNNING','PASSED',{evidence:{checksPassed:3,checksFailed:0,artifactRefs:['report:restore-001']}})==='PASSED','recovery drill evidence gate');

const budgetPolicy=defaultBudgetPolicy('g','provider.sync');
const budgetStart=budgetWindowStart(new Date('2026-08-14T12:34:56.000Z'),3600);ok(budgetStart.toISOString()==='2026-08-14T12:00:00.000Z','budget window is deterministic');
const budgetAllow=previewBudgetDecision({policy:budgetPolicy,usedBefore:0,units:1,now:new Date('2026-08-14T12:00:01.000Z')});ok(budgetAllow.decision==='ALLOW'&&budgetAllow.usedAfter===1,'budget allows in-window optional work');
const budgetDefer=previewBudgetDecision({policy:{...budgetPolicy,maxUnits:2},usedBefore:2,units:1,now:new Date('2026-08-14T12:15:00.000Z')});ok(budgetDefer.decision==='DEFER'&&budgetDefer.retryAt==='2026-08-14T13:00:00.000Z'&&budgetDefer.usedAfter===2,'enforced budget defers without consuming units');
const budgetObserve=previewBudgetDecision({policy:{...budgetPolicy,mode:'OBSERVE',maxUnits:2},usedBefore:2,units:1,now:new Date('2026-08-14T12:15:00.000Z')});ok(budgetObserve.decision==='OBSERVE_OVER'&&budgetObserve.usedAfter===3,'observe budget records overage without blocking');
ok(compareJobFairness({inFlight:0,recentStarts:0,priority:50,createdAtMs:2},{inFlight:1,recentStarts:0,priority:60,createdAtMs:1})<0,'fair queue prefers lower in-flight guild inside the same priority lane');
ok(compareJobFairness({inFlight:0,recentStarts:1,priority:50,createdAtMs:2},{inFlight:0,recentStarts:2,priority:60,createdAtMs:1})<0,'fair queue smooths recent guild starts inside the same priority lane');
ok(compareJobFairness({inFlight:0,recentStarts:0,priority:60,createdAtMs:2},{inFlight:0,recentStarts:0,priority:50,createdAtMs:1})<0,'fair queue preserves priority inside equal fairness bucket');
ok(jobPriorityBand(95)===0&&compareJobFairness({inFlight:5,recentStarts:20,priority:95,createdAtMs:2},{inFlight:0,recentStarts:0,priority:60,createdAtMs:1})<0,'critical priority lane bypasses tenant fairness');
ok(RESOURCE_BUDGET_KEYS.length===5&&validateBudgetKey('PROVIDER.SYNC')==='provider.sync','budget registry is bounded and normalized');
rejected=false;try{validateBudgetKey('custom.unregistered');}catch{rejected=true;}ok(rejected,'unregistered budget keys fail closed');
const setupBudgetDefaults=defaultSetupDraft().budgets;ok(setupBudgetDefaults.providerSync.maxUnits===24&&setupBudgetDefaults.notificationFanout.mode==='OBSERVE'&&setupBudgetDefaults.backup.windowSeconds===86400,'setup budget defaults align with runtime defaults');
const automationRule=validateAutomationRuleDefinition({eventType:'member.join',conditions:[{path:'member.level',operator:'GTE',value:5}],actions:[{type:'NOTIFY_TOPIC',config:{topic:'UPDATES',title:'Member milestone',body:'A configured member event matched a safe automation rule.'}}]});ok(matchAutomationRule({ruleId:'r',...automationRule},'member.join',{member:{level:7}}),'automation rule matches bounded event payload');
rejected=false;try{validateAutomationAction({type:'HTTP_REQUEST',config:{url:'https://example.com'}});}catch{rejected=true;}ok(rejected,'generic automation blocks arbitrary HTTP action');
rejected=false;try{validateAutomationAction({type:'NOTIFY_TOPIC',config:{topic:'SECURITY',title:'spoof',body:'blocked'}});}catch{rejected=true;}ok(rejected,'generic automation cannot impersonate security notification path');


const admissionBalanced=defaultAdmissionPolicy('g','BALANCED');
ok(evaluateAdmission(admissionBalanced,{pressure:'NORMAL',criticalIncidentOpen:false,maintenanceActive:false,operation:'STRUCTURAL'}).decision==='ALLOW','admission allows balanced structural work at normal pressure');
ok(evaluateAdmission(admissionBalanced,{pressure:'THROTTLE',criticalIncidentOpen:false,maintenanceActive:false,operation:'STRUCTURAL'}).decision==='DEFER','admission defers structural work under throttle pressure');
ok(evaluateAdmission(admissionBalanced,{pressure:'EMERGENCY',criticalIncidentOpen:true,maintenanceActive:false,operation:'SAFETY'}).decision==='ALLOW','admission never sheds safety path');
const admissionObserve={...admissionBalanced,mode:'OBSERVE'};const observedAdmission=evaluateAdmission(admissionObserve,{pressure:'EMERGENCY',criticalIncidentOpen:true,maintenanceActive:false,operation:'BULK'});ok(observedAdmission.decision==='ALLOW'&&observedAdmission.wouldDecision==='DEFER','admission observe mode records would-defer without blocking');
ok(evaluateAdmission(admissionBalanced,{pressure:'UNKNOWN',criticalIncidentOpen:false,maintenanceActive:false,operation:'STRUCTURAL'}).decision==='DEFER','admission fails closed for high-impact unknown evidence');
ok(evaluateAdmission({...admissionBalanced,preset:'MAX_AVAILABILITY'},{pressure:'WATCH',criticalIncidentOpen:false,maintenanceActive:false,operation:'BULK'}).decision==='ALLOW','max availability still admits bounded bulk work at watch pressure');
console.log(`domain-smoke PASS ${n} assertions`);
