import { randomUUID } from 'node:crypto';
import type { Database } from '@autoserver/database';

export type CreatorContentStatus='DRAFT'|'REVIEW'|'APPROVED'|'REJECTED'|'PUBLISHED'|'ARCHIVED';
const transitions:Record<CreatorContentStatus,readonly CreatorContentStatus[]>={DRAFT:['REVIEW','ARCHIVED'],REVIEW:['APPROVED','REJECTED'],APPROVED:['PUBLISHED','ARCHIVED'],REJECTED:['REVIEW','ARCHIVED'],PUBLISHED:['ARCHIVED'],ARCHIVED:[]};
export function transitionCreatorContent(current:CreatorContentStatus,next:CreatorContentStatus){if(!transitions[current].includes(next)) throw new Error(`INVALID_CREATOR_CONTENT_TRANSITION:${current}->${next}`);return next;}
function safeUrl(value?:string){if(!value) return undefined; const url=new URL(value); if(!['https:','http:'].includes(url.protocol)) throw new Error('CREATOR_URL_PROTOCOL_INVALID'); return url.toString();}

export class CreatorRepository{
  constructor(private readonly database:Database){}
  async submitContent(input:{guildId:string;authorUserId:string;contentType:string;title:string;body:string;externalUrl?:string}){const title=input.title.trim();const body=input.body.trim();if(title.length<3||title.length>120)throw new Error('CREATOR_TITLE_INVALID');if(body.length<10||body.length>4000)throw new Error('CREATOR_BODY_INVALID');const contentId=randomUUID();await this.database.requirePool().query(`insert into creator_content_items(content_id,guild_id,author_user_id,content_type,title,body,external_url,status) values($1,$2,$3,$4,$5,$6,$7,'REVIEW')`,[contentId,input.guildId,input.authorUserId,input.contentType.trim().toUpperCase().slice(0,40),title,body,safeUrl(input.externalUrl)]);return contentId;}
  async get(guildId:string,contentId:string){return (await this.database.requirePool().query<any>(`select * from creator_content_items where guild_id=$1 and content_id=$2`,[guildId,contentId])).rows[0] ?? null;}
  async listPending(guildId:string,limit=20){return (await this.database.requirePool().query<any>(`select content_id,author_user_id,content_type,title,status,created_at from creator_content_items where guild_id=$1 and status='REVIEW' order by created_at asc limit $2`,[guildId,Math.max(1,Math.min(50,limit))])).rows;}
  async review(input:{guildId:string;contentId:string;reviewerUserId:string;decision:'APPROVED'|'REJECTED';reason?:string}){return this.database.transaction(async(client)=>{const row=(await client.query<any>(`select * from creator_content_items where guild_id=$1 and content_id=$2 for update`,[input.guildId,input.contentId])).rows[0];if(!row)throw new Error('CREATOR_CONTENT_NOT_FOUND');transitionCreatorContent(row.status,input.decision);await client.query(`update creator_content_items set status=$3,reviewer_user_id=$4,review_reason=$5,updated_at=now() where guild_id=$1 and content_id=$2`,[input.guildId,input.contentId,input.decision,input.reviewerUserId,input.reason??null]);return {...row,status:input.decision};});}
  async markPublished(input:{guildId:string;contentId:string;messageId:string}){const result=await this.database.requirePool().query(`update creator_content_items set status='PUBLISHED',published_message_id=$3,published_at=now(),scheduled_at=null,updated_at=now() where guild_id=$1 and content_id=$2 and status='APPROVED'`,[input.guildId,input.contentId,input.messageId]);if(!result.rowCount)throw new Error('CREATOR_CONTENT_NOT_PUBLISHABLE');}
  async schedulePublish(input:{guildId:string;contentId:string;runAt:Date;channelKey:string}){if(!Number.isFinite(input.runAt.getTime()))throw new Error('CREATOR_SCHEDULE_INVALID');const key=input.channelKey.trim().toUpperCase();if(!/^CH_[A-Z0-9_]{2,80}$/.test(key))throw new Error('CREATOR_CHANNEL_KEY_INVALID');const result=await this.database.requirePool().query(`update creator_content_items set scheduled_at=$3,publish_channel_key=$4,updated_at=now() where guild_id=$1 and content_id=$2 and status='APPROVED' returning content_id,scheduled_at,publish_channel_key`,[input.guildId,input.contentId,input.runAt,key]);if(!result.rowCount)throw new Error('CREATOR_CONTENT_NOT_SCHEDULABLE');return result.rows[0];}
  async cancelScheduledPublish(input:{guildId:string;contentId:string}){const result=await this.database.requirePool().query(`update creator_content_items set scheduled_at=null,publish_channel_key=null,updated_at=now() where guild_id=$1 and content_id=$2 and status='APPROVED' and scheduled_at is not null returning content_id`,[input.guildId,input.contentId]);return Boolean(result.rowCount);}
  async createCollaboration(input:{guildId:string;ownerUserId:string;title:string;description:string;availability?:Record<string,unknown>}){if(input.title.trim().length<3||input.description.trim().length<10)throw new Error('COLLABORATION_INVALID');const collaborationId=randomUUID();await this.database.requirePool().query(`insert into creator_collaborations(collaboration_id,guild_id,owner_user_id,title,description,status,participant_ids,availability) values($1,$2,$3,$4,$5,'OPEN',$6,$7)`,[collaborationId,input.guildId,input.ownerUserId,input.title.trim().slice(0,120),input.description.trim().slice(0,3000),[input.ownerUserId],input.availability??{}]);return collaborationId;}
}
