import {
  ActionRowBuilder,
  ButtonStyle,
  ChannelType,
  ModalBuilder,
  PermissionFlagsBits,
  TextInputBuilder,
  TextInputStyle,
  type ButtonInteraction,
  type ModalSubmitInteraction,
} from 'discord.js';
import { CreatorRepository } from '@autoserver/creator';
import { EducationRepository } from '@autoserver/education';
import { BusinessRepository } from '@autoserver/business';
import { ResourceMappingRepository, AuditRepository, type Database } from '@autoserver/database';
import { v2NoticePanel } from '@autoserver/panels';
import { newCorrelationId } from '@autoserver/core';
import { randomUUID } from 'node:crypto';
import { ScheduledTaskRepository } from '@autoserver/scheduler';
import { VerticalOpsService } from '@autoserver/vertical-ops';
import { safeDiscordError } from './presentation.js';
import { presentSystemValue } from '@autoserver/localization';

export interface DomainActionDependencies { database: Database; }
function field(id:string,label:string,style:TextInputStyle,opts:{required?:boolean;placeholder?:string;min?:number;max?:number}={}){const v=new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(opts.required??true);if(opts.placeholder)v.setPlaceholder(opts.placeholder);if(opts.min!==undefined)v.setMinLength(opts.min);if(opts.max!==undefined)v.setMaxLength(opts.max);return new ActionRowBuilder<TextInputBuilder>().addComponents(v);}
async function mappings(database:Database,guildId:string){return new Map((await new ResourceMappingRepository(database).list(guildId)).map((r)=>[r.logicalKey,r.discordId]));}
function manager(i:ButtonInteraction|ModalSubmitInteraction){return i.inCachedGuild()&&(i.user.id===i.guild.ownerId||i.member.permissions.has(PermissionFlagsBits.ManageGuild));}
async function creatorAllowed(i:ButtonInteraction|ModalSubmitInteraction,database:Database){if(!i.inCachedGuild())return false;if(manager(i))return true;const ids=await mappings(database,i.guild.id);return ['ROLE_CREATOR','ROLE_STREAMER','ROLE_ARTIST','ROLE_CONTENT_MANAGER'].some((k)=>{const id=ids.get(k);return Boolean(id&&i.member.roles.cache.has(id));});}
async function mentorAllowed(i:ButtonInteraction|ModalSubmitInteraction,database:Database){if(!i.inCachedGuild())return false;if(manager(i))return true;const ids=await mappings(database,i.guild.id);const roleId=ids.get('ROLE_MENTOR');return Boolean(roleId&&i.member.roles.cache.has(roleId));}
async function audit(database:Database,i:ButtonInteraction|ModalSubmitInteraction,action:string,type:string,id:string,state?:Record<string,unknown>){await new AuditRepository(database).record({auditId:randomUUID(),guildId:i.guild!.id,actorId:i.user.id,action,resourceType:type,resourceId:id,afterState:state,result:'SUCCEEDED',correlationId:newCorrelationId()});}

export async function handleDomainButton(interaction:ButtonInteraction,deps:DomainActionDependencies):Promise<boolean>{
  if(!interaction.inCachedGuild())return false;const id=interaction.customId;if(!id.startsWith('creator:')&&!id.startsWith('education:')&&!id.startsWith('business:'))return false;if(!deps.database.configured){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ขั้นตอนนี้ต้องใช้ `DATABASE_URL`',tone:'primary',ephemeral:true}));return true;}
  try{
    if(id==='creator:submit'){if(!await creatorAllowed(interaction,deps.database)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมียศครีเอเตอร์ที่ระบบจัดการ หรือมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('creator:submit:modal').setTitle('ส่งผลงานครีเอเตอร์');m.addComponents(field('type','ประเภทเนื้อหา',TextInputStyle.Short,{placeholder:'เช่น VIDEO / STREAM / POST',min:3,max:40}),field('title','ชื่อเรื่อง',TextInputStyle.Short,{min:3,max:120}),field('body','คำอธิบาย',TextInputStyle.Paragraph,{min:10,max:4000}),field('url','URL สาธารณะ (ไม่บังคับ)',TextInputStyle.Short,{required:false,max:500}));await interaction.showModal(m);return true;}
    if(id==='creator:collab'){if(!await creatorAllowed(interaction,deps.database)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมียศครีเอเตอร์ที่ระบบจัดการ หรือมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('creator:collab:modal').setTitle('คำขอร่วมงานที่เปิดอยู่');m.addComponents(field('title','ชื่อความร่วมมือ',TextInputStyle.Short,{min:3,max:120}),field('description','ต้องการผู้ร่วมงานแบบใด',TextInputStyle.Paragraph,{min:10,max:3000}),field('availability','ช่วงเวลาที่สะดวก',TextInputStyle.Short,{required:false,max:300}));await interaction.showModal(m);return true;}
    if(id==='creator:review'||id==='creator:publish'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId(`${id}:modal`).setTitle(id==='creator:review'?'ตรวจผลงานครีเอเตอร์':'เผยแพร่ผลงานที่อนุมัติแล้ว');m.addComponents(field('id','UUID เนื้อหา',TextInputStyle.Short,{min:36,max:36}));if(id==='creator:review')m.addComponents(field('decision','APPROVED หรือ REJECTED',TextInputStyle.Short,{min:8,max:8}),field('reason','เหตุผลการตรวจสอบ (ไม่บังคับ)',TextInputStyle.Paragraph,{required:false,max:1000}));await interaction.showModal(m);return true;}
    if(id==='creator:schedule'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('creator:schedule:modal').setTitle('กำหนดเวลาเนื้อหาที่อนุมัติแล้ว');m.addComponents(field('id','UUID เนื้อหา',TextInputStyle.Short,{min:36,max:36}),field('when','เวลา ISO หรือ Unix timestamp',TextInputStyle.Short,{placeholder:'เช่น 2026-08-20T19:00:00+07:00',min:10,max:64}),field('channel','ช่องปลายทางเชิงตรรกะ',TextInputStyle.Short,{required:false,placeholder:'เช่น CH_UPLOADS',max:80}));await interaction.showModal(m);return true;}
    if(id==='creator:cancel-schedule'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('creator:cancel-schedule:modal').setTitle('ยกเลิกเนื้อหาที่กำหนดเวลา');m.addComponents(field('id','UUID เนื้อหา',TextInputStyle.Short,{min:36,max:36}));await interaction.showModal(m);return true;}
    if(id==='education:resource'){const m=new ModalBuilder().setCustomId('education:resource:modal').setTitle('ส่งทรัพยากรการเรียนรู้');m.addComponents(field('subject','หัวข้อ',TextInputStyle.Short,{min:2,max:80}),field('title','ชื่อทรัพยากร',TextInputStyle.Short,{min:3,max:160}),field('url','URL (ไม่บังคับ)',TextInputStyle.Short,{required:false,max:500}),field('notes','หมายเหตุ',TextInputStyle.Paragraph,{required:false,max:3000}));await interaction.showModal(m);return true;}
    if(id==='education:mentor'){const m=new ModalBuilder().setCustomId('education:mentor:modal').setTitle('ขอผู้ดูแลการเรียนรู้');m.addComponents(field('subject','หัวข้อ',TextInputStyle.Short,{min:2,max:100}),field('goal','เป้าหมายการเรียนรู้',TextInputStyle.Paragraph,{min:10,max:2000}),field('availability','ช่วงเวลาที่สะดวก',TextInputStyle.Short,{required:false,max:500}));await interaction.showModal(m);return true;}
    if(id==='education:review'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('education:review:modal').setTitle('ตรวจสอบทรัพยากรการเรียนรู้');m.addComponents(field('id','UUID ทรัพยากร',TextInputStyle.Short,{min:36,max:36}),field('decision','PUBLISHED หรือ REJECTED',TextInputStyle.Short,{min:8,max:9}));await interaction.showModal(m);return true;}
    if(id==='education:mentor:claim'){if(!await mentorAllowed(interaction,deps.database)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมียศผู้ดูแลการเรียนรู้ที่ระบบจัดการ หรือมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('education:mentor:claim:modal').setTitle('รับคำขอผู้ดูแลการเรียนรู้');m.addComponents(field('id','UUID คำขอผู้ดูแลการเรียนรู้',TextInputStyle.Short,{min:36,max:36}));await interaction.showModal(m);return true;}
    if(id==='education:mentor:schedule'){if(!await mentorAllowed(interaction,deps.database)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องเป็นผู้ดูแลการเรียนรู้ที่ได้รับมอบหมาย หรือมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('education:mentor:schedule:modal').setTitle('กำหนดเวลาเซสชันผู้ดูแลการเรียนรู้');m.addComponents(field('id','UUID คำขอผู้ดูแลการเรียนรู้',TextInputStyle.Short,{min:36,max:36}),field('when','เวลา ISO หรือ Unix timestamp',TextInputStyle.Short,{placeholder:'เช่น 2026-08-20T19:00:00+07:00',min:10,max:64}),field('timezone','เขตเวลา IANA',TextInputStyle.Short,{placeholder:'เช่น Asia/Bangkok',min:3,max:80}));await interaction.showModal(m);return true;}
    if(id==='education:mentor:complete'){if(!await mentorAllowed(interaction,deps.database)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องเป็นผู้ดูแลการเรียนรู้ที่ได้รับมอบหมาย หรือมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('education:mentor:complete:modal').setTitle('จบเซสชันผู้ดูแลการเรียนรู้');m.addComponents(field('id','UUID คำขอผู้ดูแลการเรียนรู้',TextInputStyle.Short,{min:36,max:36}));await interaction.showModal(m);return true;}
    if(id==='business:catalog'){const rows=await new BusinessRepository(deps.database).listActive(interaction.guild.id,20);const text=rows.length?rows.map((r:any)=>`**${r.name}**\n${String(r.description).slice(0,220)}${r.public_url?`\n${r.public_url}`:''}`).join('\n\n'):'ยังไม่มีรายการที่เผยแพร่และเปิดใช้งาน';await interaction.reply(v2NoticePanel({title:'รายการผลิตภัณฑ์และบริการ',description:`${text.slice(0,4000)}\n\n-# แผงนี้จะไม่ขอข้อมูลรับรองการชำระเงิน`,tone:'warning',ephemeral:true}));return true;}
    if(id==='business:item'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('business:item:modal').setTitle('เผยแพร่รายการในสารบัญ');m.addComponents(field('key','คีย์รายการแบบคงที่',TextInputStyle.Short,{min:2,max:60}),field('name','ชื่อ',TextInputStyle.Short,{min:2,max:120}),field('description','คำอธิบาย',TextInputStyle.Paragraph,{min:10,max:2000}),field('url','URL สาธารณะ (ไม่บังคับ)',TextInputStyle.Short,{required:false,max:500}));await interaction.showModal(m);return true;}
    if(id==='business:support'){const m=new ModalBuilder().setCustomId('business:support:modal').setTitle('คำขอช่วยเหลือด้านบริการ');m.addComponents(field('ref','รหัสคำสั่งซื้อ/อ้างอิง (ไม่บังคับ)',TextInputStyle.Short,{required:false,max:100}),field('issue','รายละเอียดปัญหา — ห้ามใส่ข้อมูลบัตรหรือข้อมูลรับรองการชำระเงิน',TextInputStyle.Paragraph,{min:10,max:3000}));await interaction.showModal(m);return true;}
    if(id==='business:support:queue'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const rows=await new BusinessRepository(deps.database).listOpenSupport(interaction.guild.id,20);const text=rows.length?rows.map((r:any)=>`\`${r.support_ref_id}\` · **${presentSystemValue(r.priority)}** · ${presentSystemValue(r.status)}\n${String(r.issue).slice(0,160)}${r.external_ref_masked?` · รหัสอ้างอิง ${r.external_ref_masked}`:''}`).join('\n\n'):'ไม่มีคำขอช่วยเหลือด้านบริการที่เปิดอยู่';await interaction.reply(v2NoticePanel({title:'คิวช่วยเหลือด้านบริการ',description:`${text.slice(0,4000)}\n\n-# ระบบไม่จัดเก็บข้อมูลรับรองการชำระเงิน`,tone:'warning',ephemeral:true}));return true;}
    if(id==='business:support:claim'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('business:support:claim:modal').setTitle('รับเรื่องช่วยเหลือด้านบริการ');m.addComponents(field('id','UUID คำขอช่วยเหลือ',TextInputStyle.Short,{min:36,max:36}));await interaction.showModal(m);return true;}
    if(id==='business:support:resolve'){if(!manager(interaction)){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ต้องมีสิทธิ์จัดการเซิร์ฟเวอร์',tone:'primary',ephemeral:true}));return true;}const m=new ModalBuilder().setCustomId('business:support:resolve:modal').setTitle('ปิดเรื่องช่วยเหลือด้านบริการ');m.addComponents(field('id','UUID คำขอช่วยเหลือ',TextInputStyle.Short,{min:36,max:36}),field('next','สถานะ RESOLVED หรือ CLOSED',TextInputStyle.Short,{min:6,max:8}));await interaction.showModal(m);return true;}
  }catch(error){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:safeDiscordError(error,{fallback:'การดำเนินการของระบบย่อยล้มเหลวอย่างปลอดภัย'}),tone:'primary',ephemeral:true}));return true;}return false;
}

export async function handleDomainModal(interaction:ModalSubmitInteraction,deps:DomainActionDependencies):Promise<boolean>{
  if(!interaction.inCachedGuild()||(!interaction.customId.startsWith('creator:')&&!interaction.customId.startsWith('education:')&&!interaction.customId.startsWith('business:')))return false;if(!deps.database.configured){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ขั้นตอนนี้ต้องใช้ `DATABASE_URL`',tone:'primary',ephemeral:true}));return true;}
  try{
    const id=interaction.customId;
    if(id==='creator:submit:modal'){if(!await creatorAllowed(interaction,deps.database))throw new Error('CREATOR_ROLE_REQUIRED');const contentId=await new CreatorRepository(deps.database).submitContent({guildId:interaction.guild.id,authorUserId:interaction.user.id,contentType:interaction.fields.getTextInputValue('type'),title:interaction.fields.getTextInputValue('title'),body:interaction.fields.getTextInputValue('body'),externalUrl:interaction.fields.getTextInputValue('url').trim()||undefined});await audit(deps.database,interaction,'CREATOR_CONTENT_SUBMIT','CREATOR_CONTENT',contentId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`ส่งเนื้อหาครีเอเตอร์ให้ตรวจสอบแล้ว รหัส: \`${contentId}\``,tone:'primary',ephemeral:true}));return true;}
    if(id==='creator:collab:modal'){if(!await creatorAllowed(interaction,deps.database))throw new Error('CREATOR_ROLE_REQUIRED');const collaborationId=await new CreatorRepository(deps.database).createCollaboration({guildId:interaction.guild.id,ownerUserId:interaction.user.id,title:interaction.fields.getTextInputValue('title'),description:interaction.fields.getTextInputValue('description'),availability:{text:interaction.fields.getTextInputValue('availability').trim()}});const map=await mappings(deps.database,interaction.guild.id);const channelId=map.get('CH_COLLABORATIONS');if(channelId){const channel=await interaction.guild.channels.fetch(channelId).catch(()=>null);if(channel?.type===ChannelType.GuildText)await channel.send({...v2NoticePanel({title:interaction.fields.getTextInputValue('title'),description:`${interaction.fields.getTextInputValue('description')}\n\n-# ความร่วมมือ ${collaborationId}`,tone:'violet'}),allowedMentions:{parse:[]}});}await audit(deps.database,interaction,'CREATOR_COLLAB_OPEN','CREATOR_COLLAB',collaborationId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`เปิดความร่วมมือแล้ว รหัส: \`${collaborationId}\``,tone:'primary',ephemeral:true}));return true;}
    if(id==='creator:review:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const contentId=interaction.fields.getTextInputValue('id').trim();const decision=interaction.fields.getTextInputValue('decision').trim().toUpperCase();if(!['APPROVED','REJECTED'].includes(decision))throw new Error('CREATOR_REVIEW_DECISION_INVALID');await new CreatorRepository(deps.database).review({guildId:interaction.guild.id,contentId,reviewerUserId:interaction.user.id,decision:decision as 'APPROVED'|'REJECTED',reason:interaction.fields.getTextInputValue('reason').trim()||undefined});await audit(deps.database,interaction,'CREATOR_CONTENT_REVIEW','CREATOR_CONTENT',contentId,{decision});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`อัปเดตสถานะเนื้อหาเป็น **${presentSystemValue(decision)}** แล้ว`,tone:'primary',ephemeral:true}));return true;}
    if(id==='creator:publish:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const contentId=interaction.fields.getTextInputValue('id').trim();const repo=new CreatorRepository(deps.database);const content=await repo.get(interaction.guild.id,contentId);if(!content||content.status!=='APPROVED')throw new Error('CREATOR_CONTENT_NOT_APPROVED');const map=await mappings(deps.database,interaction.guild.id);const channelId=map.get('CH_UPLOADS')??map.get('CH_CREATOR_ANNOUNCEMENTS');if(!channelId)throw new Error('CREATOR_PUBLISH_CHANNEL_NOT_MAPPED');const channel=await interaction.guild.channels.fetch(channelId);if(!channel||channel.type!==ChannelType.GuildText)throw new Error('CREATOR_PUBLISH_CHANNEL_INVALID');const sent=await channel.send({...v2NoticePanel({title:content.title,description:`${content.body}\n\n**${content.external_url?'ลิงก์':'ประเภท'}** ${content.external_url??content.content_type}\n\n-# เนื้อหาครีเอเตอร์ ${contentId}`,tone:'violet'}),allowedMentions:{parse:[]}});await repo.markPublished({guildId:interaction.guild.id,contentId,messageId:sent.id});await audit(deps.database,interaction,'CREATOR_CONTENT_PUBLISH','CREATOR_CONTENT',contentId,{messageId:sent.id});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`เผยแพร่ไปยัง <#${channel.id}>.`,tone:'primary',ephemeral:true}));return true;}
    if(id==='creator:schedule:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const contentId=interaction.fields.getTextInputValue('id').trim();const channelKey=interaction.fields.getTextInputValue('channel').trim()||'CH_UPLOADS';const result=await new VerticalOpsService(deps.database).scheduleCreator({guildId:interaction.guild.id,contentId,runAt:interaction.fields.getTextInputValue('when'),channelKey,timezone:'UTC'});await audit(deps.database,interaction,'CREATOR_CONTENT_SCHEDULE','CREATOR_CONTENT',contentId,{runAt:result.runAt.toISOString(),channelKey:result.channelKey,taskId:result.taskId});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`กำหนดเวลาเนื้อหาครีเอเตอร์ไว้ที่ <t:${Math.floor(result.runAt.getTime()/1000)}:F>.`,tone:'primary',ephemeral:true}));return true;}
    if(id==='creator:cancel-schedule:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const contentId=interaction.fields.getTextInputValue('id').trim();const result=await new VerticalOpsService(deps.database).cancelCreatorSchedule({guildId:interaction.guild.id,contentId});if(!result.cancelled)throw new Error('CREATOR_CONTENT_NOT_SCHEDULED');await audit(deps.database,interaction,'CREATOR_CONTENT_SCHEDULE_CANCEL','CREATOR_CONTENT',contentId,{taskCancelled:result.taskCancelled});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ยกเลิกการเผยแพร่ผลงานครีเอเตอร์ตามกำหนดแล้ว',tone:'primary',ephemeral:true}));return true;}
    if(id==='education:resource:modal'){const repo=new EducationRepository(deps.database);const resourceId=await repo.submitResource({guildId:interaction.guild.id,userId:interaction.user.id,subject:interaction.fields.getTextInputValue('subject'),title:interaction.fields.getTextInputValue('title'),url:interaction.fields.getTextInputValue('url').trim()||undefined,notes:interaction.fields.getTextInputValue('notes').trim()||undefined});await audit(deps.database,interaction,'EDUCATION_RESOURCE_SUBMIT','EDUCATION_RESOURCE',resourceId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`ส่งทรัพยากรให้ตรวจสอบแล้ว รหัส: \`${resourceId}\``,tone:'primary',ephemeral:true}));return true;}
    if(id==='education:mentor:modal'){const requestId=await new EducationRepository(deps.database).createMentorRequest({guildId:interaction.guild.id,requesterUserId:interaction.user.id,subject:interaction.fields.getTextInputValue('subject'),goal:interaction.fields.getTextInputValue('goal'),availability:interaction.fields.getTextInputValue('availability').trim()||undefined});await audit(deps.database,interaction,'MENTOR_REQUEST_CREATE','MENTOR_REQUEST',requestId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`เปิดคำขอผู้ดูแลการเรียนรู้แล้ว รหัส: \`${requestId}\``,tone:'primary',ephemeral:true}));return true;}
    if(id==='education:mentor:claim:modal'){if(!await mentorAllowed(interaction,deps.database))throw new Error('MENTOR_ROLE_REQUIRED');const requestId=interaction.fields.getTextInputValue('id').trim();await new EducationRepository(deps.database).claimMentorRequest({guildId:interaction.guild.id,requestId,mentorUserId:interaction.user.id});await audit(deps.database,interaction,'MENTOR_REQUEST_CLAIM','MENTOR_REQUEST',requestId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'รับคำขอผู้ดูแลการเรียนรู้แล้ว',tone:'primary',ephemeral:true}));return true;}
    if(id==='education:mentor:schedule:modal'){if(!await mentorAllowed(interaction,deps.database))throw new Error('MENTOR_ROLE_REQUIRED');const requestId=interaction.fields.getTextInputValue('id').trim();const repo=new EducationRepository(deps.database);const request=await repo.getMentorRequest(interaction.guild.id,requestId);if(!request)throw new Error('MENTOR_REQUEST_NOT_FOUND');if(!manager(interaction)&&request.mentor_user_id!==interaction.user.id)throw new Error('MENTOR_REQUEST_NOT_ASSIGNED_TO_ACTOR');const timezone=interaction.fields.getTextInputValue('timezone').trim();const result=await new VerticalOpsService(deps.database).scheduleMentor({guildId:interaction.guild.id,requestId,runAt:interaction.fields.getTextInputValue('when'),timezone});await audit(deps.database,interaction,'MENTOR_REQUEST_SCHEDULE','MENTOR_REQUEST',requestId,{scheduledAt:result.runAt.toISOString(),timezone,reminderTasks:result.reminderTaskIds.length});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`กำหนดเวลาเซสชันผู้ดูแลการเรียนรู้ไว้ที่ <t:${Math.floor(result.runAt.getTime()/1000)}:F>.`,tone:'primary',ephemeral:true}));return true;}
    if(id==='education:mentor:complete:modal'){if(!await mentorAllowed(interaction,deps.database))throw new Error('MENTOR_ROLE_REQUIRED');const requestId=interaction.fields.getTextInputValue('id').trim();const repo=new EducationRepository(deps.database);const request=await repo.getMentorRequest(interaction.guild.id,requestId);if(!request)throw new Error('MENTOR_REQUEST_NOT_FOUND');if(!manager(interaction)&&request.mentor_user_id!==interaction.user.id)throw new Error('MENTOR_REQUEST_NOT_ASSIGNED_TO_ACTOR');await new VerticalOpsService(deps.database).completeMentor({guildId:interaction.guild.id,requestId,actorId:interaction.user.id,manager:manager(interaction)});await audit(deps.database,interaction,'MENTOR_REQUEST_COMPLETE','MENTOR_REQUEST',requestId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'ทำเครื่องหมายเซสชันผู้ดูแลการเรียนรู้ว่าเสร็จแล้ว',tone:'primary',ephemeral:true}));return true;}
    if(id==='education:review:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const resourceId=interaction.fields.getTextInputValue('id').trim();const decision=interaction.fields.getTextInputValue('decision').trim().toUpperCase();if(!['PUBLISHED','REJECTED'].includes(decision))throw new Error('EDUCATION_REVIEW_DECISION_INVALID');const repo=new EducationRepository(deps.database);const resource=await repo.getResource(interaction.guild.id,resourceId);if(!resource||resource.status!=='REVIEW')throw new Error('EDUCATION_RESOURCE_NOT_REVIEWABLE');if(decision==='PUBLISHED'){const map=await mappings(deps.database,interaction.guild.id);const channelId=map.get('CH_RESOURCES');if(!channelId)throw new Error('EDUCATION_RESOURCE_CHANNEL_NOT_MAPPED');const channel=await interaction.guild.channels.fetch(channelId);if(!channel||channel.type!==ChannelType.GuildText)throw new Error('EDUCATION_RESOURCE_CHANNEL_INVALID');await channel.send({...v2NoticePanel({title:resource.title,description:`${[`หัวข้อ: **${resource.subject}**`,resource.notes,resource.url].filter(Boolean).join('\n\n')}\n\n-# ทรัพยากร ${resourceId}`,tone:'ice'}),allowedMentions:{parse:[]}});}await repo.reviewResource({guildId:interaction.guild.id,resourceId,reviewerUserId:interaction.user.id,decision:decision as 'PUBLISHED'|'REJECTED'});await audit(deps.database,interaction,'EDUCATION_RESOURCE_REVIEW','EDUCATION_RESOURCE',resourceId,{decision});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`อัปเดตสถานะทรัพยากรเป็น **${presentSystemValue(decision)}** แล้ว`,tone:'primary',ephemeral:true}));return true;}
    if(id==='business:item:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const key=await new BusinessRepository(deps.database).upsertCatalogItem({guildId:interaction.guild.id,createdBy:interaction.user.id,itemKey:interaction.fields.getTextInputValue('key'),name:interaction.fields.getTextInputValue('name'),description:interaction.fields.getTextInputValue('description'),publicUrl:interaction.fields.getTextInputValue('url').trim()||undefined,status:'ACTIVE'});await audit(deps.database,interaction,'BUSINESS_ITEM_UPSERT','BUSINESS_ITEM',key);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`เผยแพร่รายการในสารบัญ **${key}** แล้ว`,tone:'primary',ephemeral:true}));return true;}
    if(id==='business:support:modal'){const result=await new BusinessRepository(deps.database).createSupportReference({guildId:interaction.guild.id,userId:interaction.user.id,externalReference:interaction.fields.getTextInputValue('ref').trim()||undefined,issue:interaction.fields.getTextInputValue('issue')});await new ScheduledTaskRepository(deps.database).schedule({guildId:interaction.guild.id,taskType:'BUSINESS_SUPPORT_SLA_CHECK',runAt:result.slaDueAt,timezone:'UTC',dedupKey:`business-support-sla:${result.supportRefId}`,payload:{supportRefId:result.supportRefId}});await audit(deps.database,interaction,'BUSINESS_SUPPORT_CREATE','BUSINESS_SUPPORT',result.supportRefId,{maskedReference:result.masked??null,slaDueAt:result.slaDueAt.toISOString()});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`เปิดคำขอช่วยเหลือด้านบริการแล้ว เลขอ้างอิง: \`${result.supportRefId}\`${result.masked?` · เลขอ้างอิงภายนอก ${result.masked}`:''} ระบบไม่ได้จัดเก็บข้อมูลรับรองการชำระเงิน`,tone:'primary',ephemeral:true}));return true;}
    if(id==='business:support:claim:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const supportRefId=interaction.fields.getTextInputValue('id').trim();await new VerticalOpsService(deps.database).claimBusinessSupport({guildId:interaction.guild.id,supportRefId,actorId:interaction.user.id});await audit(deps.database,interaction,'BUSINESS_SUPPORT_CLAIM','BUSINESS_SUPPORT',supportRefId);await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:'รับคำขอช่วยเหลือด้านบริการแล้ว',tone:'primary',ephemeral:true}));return true;}
    if(id==='business:support:resolve:modal'){if(!manager(interaction))throw new Error('MANAGE_GUILD_REQUIRED');const supportRefId=interaction.fields.getTextInputValue('id').trim();const next=interaction.fields.getTextInputValue('next').trim().toUpperCase();if(!['RESOLVED','CLOSED'].includes(next))throw new Error('BUSINESS_SUPPORT_STATE_INVALID');await new VerticalOpsService(deps.database).resolveBusinessSupport({guildId:interaction.guild.id,supportRefId,actorId:interaction.user.id,next:next as 'RESOLVED'|'CLOSED'});await audit(deps.database,interaction,'BUSINESS_SUPPORT_RESOLVE','BUSINESS_SUPPORT',supportRefId,{next});await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:`อัปเดตสถานะคำขอช่วยเหลือด้านบริการเป็น **${presentSystemValue(next)}** แล้ว`,tone:'primary',ephemeral:true}));return true;}
  }catch(error){await interaction.reply(v2NoticePanel({title:'ศูนย์ควบคุมระบบย่อย',description:safeDiscordError(error,{fallback:'การส่งข้อมูลไปยังระบบย่อยล้มเหลวอย่างปลอดภัย'}),tone:'primary',ephemeral:true}));return true;}return false;
}
