import { useEffect, useState } from 'react';
import { thValue } from '../ui-thai';

type AuditItem={auditId:string;actorId?:string;action:string;resourceType?:string;resourceId?:string;beforeState?:unknown;afterState?:unknown;result:string;errorCode?:string;correlationId:string;createdAt:string;integrity:{state:'CHAINED'|'LEGACY_UNCHAINED';sequence?:string;eventHash?:string;algorithm?:string}};
type Page={items:AuditItem[];nextCursor?:string;redacted:true};
type Integrity={state:'HEALTHY'|'DEGRADED'|'UNINITIALIZED';coverage:'NONE'|'FULL'|'TAIL';headSequence:string;headHash:string;checkedEntries:number;recomputedEntries:number;hashOnlyEntries:number;legacyUnchainedEntries:number;legacyUnchainedCapped:boolean;unchainedAfterStart:number;unchainedAfterStartCapped:boolean;mismatchCount:number;mismatches:string[];evidenceClass:string;generatedAt?:string};

export function AuditExplorer({api,guildId,authenticated}:{api:string;guildId:string;authenticated:boolean}){
  const [search,setSearch]=useState('');const [result,setResult]=useState('');const [data,setData]=useState<Page|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [cursor,setCursor]=useState<string|undefined>();const [history,setHistory]=useState<Array<string|undefined>>([]);const [selected,setSelected]=useState<AuditItem|null>(null);const [integrity,setIntegrity]=useState<Integrity|null>(null);const [integrityBusy,setIntegrityBusy]=useState(false);
  const load=async(nextCursor=cursor)=>{if(!guildId||!authenticated){setData(null);return;}setBusy(true);try{const url=new URL(`${api}/api/guilds/${guildId}/audit`);url.searchParams.set('limit','30');if(search.trim())url.searchParams.set('search',search.trim());if(result)url.searchParams.set('result',result);if(nextCursor)url.searchParams.set('cursor',nextCursor);const response=await fetch(url,{credentials:'include'});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'ค้นหาบันทึกตรวจสอบไม่สำเร็จ');setData(body);setError(null);setSelected(null);}catch(err){setError(err instanceof Error?err.message:'ค้นหาบันทึกตรวจสอบไม่สำเร็จ');setData(null);}finally{setBusy(false);}};
  const verifyIntegrity=async()=>{if(!guildId||!authenticated){setIntegrity(null);return;}setIntegrityBusy(true);try{const response=await fetch(`${api}/api/guilds/${guildId}/audit/integrity?limit=500`,{credentials:'include'});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'ตรวจสายหลักฐานไม่สำเร็จ');setIntegrity(body);setError(null);}catch(err){setError(err instanceof Error?err.message:'ตรวจสายหลักฐานไม่สำเร็จ');setIntegrity(null);}finally{setIntegrityBusy(false);}};
  useEffect(()=>{setCursor(undefined);setHistory([]);void load(undefined);void verifyIntegrity();},[api,guildId,authenticated]);
  const apply=()=>{setCursor(undefined);setHistory([]);void load(undefined);};
  const next=()=>{if(!data?.nextCursor)return;setHistory((items)=>[...items,cursor]);setCursor(data.nextCursor);void load(data.nextCursor);};
  const previous=()=>{if(!history.length)return;const previousCursor=history.at(-1);setHistory((items)=>items.slice(0,-1));setCursor(previousCursor);void load(previousCursor);};
  return <section className="panel audit-explorer" aria-label="สำรวจบันทึกตรวจสอบ">
    <div className="panel-heading"><div><span className="kicker">สำรวจบันทึกตรวจสอบ</span><h2>ยึดรหัสสหสัมพันธ์เป็นหลักและปกปิดข้อมูลก่อนแสดง</h2></div><span className="safety-badge">จำกัดตามเซิร์ฟเวอร์</span></div>
    {!authenticated||!guildId?<div className="setup-empty">เข้าสู่ระบบและเลือกเซิร์ฟเวอร์ที่จัดการได้เพื่อดูร่องรอยการตรวจสอบ</div>:<>
      <div className={`audit-integrity-card ${integrity?.state?.toLowerCase()??'unknown'}`}>
        <div><span className="kicker">สายหลักฐานความสมบูรณ์</span><strong>{thValue(integrity?.state??'unknown')}</strong><span>{integrity?` · ${thValue(integrity.coverage)} · ปลายสาย #${integrity.headSequence}`:' · ยังไม่ได้โหลดหลักฐาน'}</span></div>
        <div>{integrity?<><span>ตรวจแล้ว {integrity.checkedEntries} · คำนวณซ้ำ {integrity.recomputedEntries} · เหลือเฉพาะแฮช {integrity.hashOnlyEntries}</span><span>ข้อมูลเดิม {integrity.legacyUnchainedEntries}{integrity.legacyUnchainedCapped?'+':''} · หลังเริ่มระบบแต่ไม่อยู่ในสาย {integrity.unchainedAfterStart}{integrity.unchainedAfterStartCapped?'+':''} · ไม่ตรงกัน {integrity.mismatchCount}</span><code>{integrity.headHash.slice(0,16)}…</code></>:null}</div>
        <button type="button" className="secondary-action compact-action" disabled={integrityBusy} onClick={()=>void verifyIntegrity()}>{integrityBusy?'กำลังตรวจ…':'ตรวจปลายสายหลักฐาน'}</button>
      </div>
      {integrity?.mismatchCount?<div className="operator-error">สายหลักฐานไม่ตรงกัน: {integrity.mismatches.slice(0,5).join(' · ')}</div>:null}
      <p className="audit-integrity-note">การตรวจนี้เป็นหลักฐานการแก้ไขข้อมูลในฐานข้อมูลเท่านั้น ไม่ใช่พื้นที่จัดเก็บแบบแก้ไม่ได้หรือการรับรองเข้ารหัสภายนอก หลังหมดช่วงเก็บรายละเอียดอาจเหลือเฉพาะแฮช</p>
      <div className="audit-filters"><label>ค้นหา<input value={search} maxLength={80} onChange={(event)=>setSearch(event.target.value)} placeholder="การกระทำ ทรัพยากร หรือข้อผิดพลาด" onKeyDown={(event)=>{if(event.key==='Enter')apply();}}/></label><label>ผลลัพธ์<select value={result} onChange={(event)=>setResult(event.target.value)}><option value="">ทุกผลลัพธ์</option><option value="SUCCEEDED">สำเร็จ</option><option value="FAILED">ล้มเหลว</option><option value="REJECTED">ถูกปฏิเสธ</option><option value="CANCELLED">ยกเลิกแล้ว</option></select></label><button type="button" className="secondary-action" disabled={busy} onClick={apply}>{busy?'กำลังค้นหา…':'ค้นหาบันทึก'}</button></div>
      {error?<div className="operator-error">{error}</div>:data?.items.length?<><div className="audit-list">{data.items.map((item)=><button type="button" key={item.auditId} className={selected?.auditId===item.auditId?'audit-row active':'audit-row'} onClick={()=>setSelected(item)}><span className={`audit-result ${item.result.toLowerCase()}`}>{thValue(item.result)}</span><strong>{item.action}</strong><span>{item.resourceType??'—'} · {item.resourceId??'—'}</span><code>{item.correlationId.slice(0,13)}…</code><span className={`audit-chain-state ${item.integrity.state==='CHAINED'?'chained':'legacy'}`}>{item.integrity.state==='CHAINED'?`สาย #${item.integrity.sequence}`:'ข้อมูลเดิม'}</span><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString('th-TH')}</time></button>)}</div><div className="audit-pager"><button type="button" className="secondary-action compact-action" disabled={!history.length||busy} onClick={previous}>ก่อนหน้า</button><span>{data.redacted?'ปกปิดข้อมูลสถานะ · ':''}{data.items.length} รายการ</span><button type="button" className="secondary-action compact-action" disabled={!data.nextCursor||busy} onClick={next}>ถัดไป</button></div></>:<div className="setup-empty">ไม่พบหลักฐานตรวจสอบที่ตรงตัวกรอง</div>}
      {selected&&<aside className="audit-detail"><div><span className="kicker">รายละเอียดหลักฐาน</span><h3>{selected.action}</h3><p><code>{selected.correlationId}</code></p><p>{selected.integrity.state==='CHAINED'?<>ลำดับสายหลักฐาน <strong>{selected.integrity.sequence}</strong> · <code>{selected.integrity.eventHash?.slice(0,20)}…</code></>:'ข้อมูลเดิมที่สร้างก่อนเริ่มใช้สายหลักฐาน'}</p></div><div className="audit-state-grid"><div><span>ก่อนหน้า · ปกปิดข้อมูล</span><pre>{JSON.stringify(selected.beforeState??null,null,2)}</pre></div><div><span>หลังจากนั้น · ปกปิดข้อมูล</span><pre>{JSON.stringify(selected.afterState??null,null,2)}</pre></div></div></aside>}
    </>}
  </section>;
}
