import { useEffect, useState } from 'react';
type Finding={key:string;severity:string;message:string};type Report={ready:boolean;node:string;packageVersion:string;compatibility:{compatible:boolean;findings:Finding[]};dependencyPolicy:{sourcePolicyReady:boolean;ready:boolean;packageCount:number;registryHosts:string[];installScriptPackages:string[];installSurfaces:Array<{name:string;path:string;mode:string}>};migrations:{count:number;latest:string|null;continuous:boolean};lockfile:boolean;unpinnedDependencies:Array<{name:string;version:unknown}>;findings:string[];generatedAt:string;evidenceClass:string};
export function ReleaseTruthConsole({api,authenticated}:{api:string;authenticated:boolean}){
 const [data,setData]=useState<Report|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const load=async()=>{if(!authenticated){setData(null);return;}setBusy(true);try{const response=await fetch(`${api}/api/release/truth`,{credentials:'include'});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'ไม่สามารถอ่านหลักฐานการเผยแพร่ได้');setData(body);setError(null);}catch(err){setError(err instanceof Error?err.message:'ไม่สามารถอ่านหลักฐานการเผยแพร่ได้');setData(null);}finally{setBusy(false);}};useEffect(()=>{void load();},[api,authenticated]);
 return <section className="panel release-truth" aria-label="หลักฐานความพร้อมเผยแพร่"><div className="panel-heading"><div><span className="kicker">ความจริงก่อนเผยแพร่</span><h2>ยังห้ามเลื่อนสถานะจนกว่าหลักฐานทุกด้านจะสอดคล้องกัน</h2></div><button type="button" className="secondary-action compact-action" disabled={busy||!authenticated} onClick={()=>void load()}>{busy?'กำลังตรวจ…':'ตรวจใหม่'}</button></div>
 {!authenticated?<div className="setup-empty">เข้าสู่ระบบเพื่อตรวจความเข้ากันได้ของรันไทม์และตัวบล็อกการเผยแพร่</div>:error?<div className="operator-error">{error}</div>:data?<><div className={data.ready?'release-verdict ready':'release-verdict blocked'}><strong>{data.ready?'ผ่าน':'ถูกบล็อก'}</strong><span>{data.ready?'เกตแบบสแตติกสอดคล้องกันแล้ว แต่หลักฐานเชื่อมต่อจริงยังต้องตรวจแยก':'ตั้งใจบล็อกการเผยแพร่แบบสแตติก เพราะการมีไฟล์ต้นฉบับอย่างเดียวไม่ใช่หลักฐานว่าเสร็จ'}</span></div>
 <div className="release-grid"><div><span>รุ่นแพ็กเกจ</span><strong>{data.packageVersion}</strong></div><div><span>รันไทม์ Node</span><strong>{data.node}</strong></div><div><span>ไมเกรชัน</span><strong>{data.migrations.count}</strong><small>{data.migrations.latest??'ไม่มี'}</small></div><div><span>ไฟล์ล็อก</span><strong>{data.lockfile?'มี':'ไม่มี'}</strong></div><div><span>นโยบายแหล่งแพ็กเกจ</span><strong>{data.dependencyPolicy.sourcePolicyReady?'ผ่าน':'ถูกบล็อก'}</strong><small>{data.dependencyPolicy.packageCount} แพ็กเกจที่ล็อก</small></div><div><span>แหล่งทะเบียน</span><strong>{data.dependencyPolicy.registryHosts.length||0}</strong><small>{data.dependencyPolicy.registryHosts.join(', ')||'รอไฟล์ล็อก'}</small></div><div><span>สคริปต์ติดตั้ง</span><strong>{data.dependencyPolicy.installScriptPackages.length}</strong><small>เป็นเพียงรายการ ต้องตรวจทานก่อนรันวงจรติดตั้ง</small></div><div><span>ความเข้ากันได้</span><strong>{data.compatibility.compatible?'เข้ากันได้':'ถูกบล็อก'}</strong></div><div><span>แพ็กเกจไม่ตรึงรุ่น</span><strong>{data.unpinnedDependencies.length}</strong></div></div>
 {data.findings.length>0?<div className="release-findings" aria-label="ตัวบล็อกการเผยแพร่">{data.findings.map((finding)=><div key={finding}><span>ตัวบล็อก</span><p>{finding}</p></div>)}</div>:<div className="setup-empty">ตัวประเมินความจริงก่อนเผยแพร่ไม่พบบล็อกเกอร์แบบสแตติก</div>}<div className="operator-foot"><span>{data.evidenceClass}</span><span>{new Date(data.generatedAt).toLocaleString('th-TH')}</span><span>หลักฐาน Discord/ฐานข้อมูล/โหลดจริงเป็นเกตแยก</span></div></>:<div className="setup-empty">ยังไม่ได้โหลดหลักฐานการเผยแพร่</div>}
 </section>;
}
