import { useEffect, useMemo, useState } from 'react';
import { thBoolean } from '../ui-thai';
type Role={id:string;name:string;position:number;permissions:string[];logicalKey:string|null;ownership:string|null};type Channel={id:string;name:string;type:number;parentId:string|null;logicalKey:string|null;ownership:string|null};type Member={userId:string;displayName:string;roleIds:string[]};
async function getJson(url:string){const response=await fetch(url,{credentials:'include'});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'เรียกข้อมูลไม่สำเร็จ');return body;}
export function StructureConsole({api,guildId,authenticated}:{api:string;guildId:string;authenticated:boolean}){
  const [roles,setRoles]=useState<Role[]>([]),[channels,setChannels]=useState<Channel[]>([]),[members,setMembers]=useState<Member[]>([]);const [channelId,setChannelId]=useState(''),[userId,setUserId]=useState(''),[explain,setExplain]=useState<any>(null),[message,setMessage]=useState('');
  const load=async()=>{if(!guildId||!authenticated)return;try{const [structure,memberData]=await Promise.all([getJson(`${api}/api/guilds/${guildId}/structure`),getJson(`${api}/api/guilds/${guildId}/members?limit=120`)]);setRoles(structure.roles??[]);setChannels(structure.channels??[]);setMembers(memberData.members??[]);setChannelId((current)=>current||structure.channels?.[0]?.id||'');setUserId((current)=>current||memberData.members?.[0]?.userId||'');setMessage(memberData.partial?'รายชื่อสมาชิกใช้แคชเกตเวย์ปัจจุบัน หากจำเป็นให้ระบุรหัสผู้ใช้โดยตรง':'');}catch(e){setMessage(e instanceof Error?e.message:'โหลดโครงสร้างไม่สำเร็จ');}};
  useEffect(()=>{void load();},[guildId,authenticated]);const dangerous=useMemo(()=>roles.filter((role)=>role.permissions.includes('Administrator')||role.permissions.includes('ManageGuild')||role.permissions.includes('ManageRoles')),[roles]);if(!authenticated||!guildId)return null;
  const runExplain=async()=>{if(!channelId||!userId)return;try{setExplain(await getJson(`${api}/api/guilds/${guildId}/permissions/explain?channelId=${encodeURIComponent(channelId)}&userId=${encodeURIComponent(userId)}`));}catch(e){setMessage(e instanceof Error?e.message:'อธิบายสิทธิ์ไม่สำเร็จ');}};
  return <section className="panel structure-console"><div className="panel-heading"><div><span className="kicker">โครงสร้างและคำอธิบายสิทธิ์</span><h2>ยึดรหัสถาวรเหนือชื่อ Discord ที่เปลี่ยนได้</h2></div><button className="secondary-action compact-action" onClick={()=>void load()}>รีเฟรชสถานะสด</button></div>
    <div className="recovery-metrics"><span><b>{roles.length}</b>ยศ</span><span><b>{channels.length}</b>ช่อง</span><span><b>{members.length}</b>สมาชิกในแคช</span><span><b>{dangerous.length}</b>ยศสิทธิ์สูง</span></div>
    <div className="structure-grid"><div><h3>ทรัพยากรที่ระบบดูแล</h3><div className="mini-resource-list">{channels.filter((item)=>item.logicalKey).slice(0,14).map((channel)=><div key={channel.id}><b>{channel.name}</b><small>{channel.logicalKey} · {channel.ownership}</small></div>)}</div></div>
      <div><h3>อธิบายการเข้าถึงของสมาชิก</h3><label>ช่อง<select value={channelId} onChange={(e)=>setChannelId(e.target.value)}>{channels.filter((c)=>c.type!==4).map((c)=><option key={c.id} value={c.id}>{c.name}{c.logicalKey?` · ${c.logicalKey}`:''}</option>)}</select></label><label>สมาชิก<select value={userId} onChange={(e)=>setUserId(e.target.value)}>{members.map((m)=><option key={m.userId} value={m.userId}>{m.displayName}</option>)}</select></label><button className="primary-action" onClick={()=>void runExplain()}>อธิบายสิทธิ์ที่ได้จริง</button>{explain&&<div className="permission-explain"><b>{explain.member.displayName} → #{explain.channel.name}</b><p>มองเห็น: {thBoolean(explain.resolved?.viewChannel)} · ส่งข้อความ: {thBoolean(explain.resolved?.sendMessages)} · เชื่อมต่อเสียง: {thBoolean(explain.resolved?.connect)}</p><small>{explain.desired?.explanation??'ช่องนี้ยังไม่มีโปรไฟล์การมองเห็นที่ระบบดูแล'}</small></div>}</div></div>{message&&<p className="recovery-note">{message}</p>}
  </section>;
}
